Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2020-08, with the labels that each got.

#33 Coscheduling fix: bound contains both assigned and assumed waiting Pods
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#35 Add make sub-command to build docker image
  .gitignore
  Makefile
  build/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#32 Clean up the expired PodGroupInfo regularly
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#38 Refine KEP structure
  OWNERS
  kep/2-lightweight-coscheduling/README.md
  kep/2-lightweight-coscheduling/design.png
  kep/2-lightweight-coscheduling/kep.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#37 Add UT for sort for PG pod and no PG pod
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#39 Fix typo
  pkg/coscheduling/coscheduling.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#41 Fix the broken coscheduling KEP link
  pkg/coscheduling/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#40 Coscheduling: make scheduling parameters configurable
  manifests/coscheduling/scheduler-config.yaml
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#43 Bump k8s deps to v1.18.8
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#10 KEP for Capacity scheduling for ML/DL workloads based on scheduler framework
  kep/9-capacity-scheduling/1.png
  kep/9-capacity-scheduling/2.png
  kep/9-capacity-scheduling/3.png
  kep/9-capacity-scheduling/4.png
  kep/9-capacity-scheduling/README.md
  kep/9-capacity-scheduling/kep.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scheduling, size/L
