Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2020-09, with the labels that each got.

#45 Bump master to 1.19
  Makefile
  cmd/main.go
  cmd/main_test.go
  go.mod
  go.sum
  hack/lib/etcd.sh
  hack/openapi-violation.list
  hack/tools.go
  hack/update-codegen.sh
  hack/update-generated-openapi.sh
  manifests/coscheduling/scheduler-config.yaml
  manifests/qos/scheduler-config.yaml
  pkg/apis/config/doc.go
  pkg/apis/config/register.go
  pkg/apis/config/scheme/scheme.go
  pkg/apis/config/types.go
  pkg/apis/config/v1beta1/defaults.go
  pkg/apis/config/v1beta1/doc.go
  pkg/apis/config/v1beta1/register.go
  pkg/apis/config/v1beta1/types.go
  pkg/apis/config/v1beta1/zz_generated.conversion.go
  pkg/apis/config/v1beta1/zz_generated.deepcopy.go
  pkg/apis/config/v1beta1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/coscheduling/README.md
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
  pkg/qos/queue_sort.go
  pkg/qos/queue_sort_test.go
  test/integration/coscheduling_test.go
  test/integration/qos_test.go
  test/util/scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#42 Add kep for coscheduling base on CRD
  kep/42-podgroup-coscheduling/README.md
  kep/42-podgroup-coscheduling/kep.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#48 Kep for node resources allocatable score plugin
  kep/48-node-resources-allocatable-scoring/README.md
  kep/48-node-resources-allocatable-scoring/kep.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#51 Container Image Builds For k8s.gcr.io
  Dockerfile
  Makefile
  cloudbuild.yaml
  doc/release-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#53 Update Container Image Documentation
  README.md
  doc/release-guide.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#36 NodeResourcesAllocatable Score plugin and tests
  cmd/main.go
  cmd/main_test.go
  go.mod
  manifests/noderesources/scheduler-config.yaml
  pkg/apis/config/register.go
  pkg/apis/config/types.go
  pkg/apis/config/v1beta1/defaults.go
  pkg/apis/config/v1beta1/register.go
  pkg/apis/config/v1beta1/types.go
  pkg/apis/config/v1beta1/zz_generated.conversion.go
  pkg/apis/config/v1beta1/zz_generated.deepcopy.go
  pkg/apis/config/v1beta1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/noderesources/README.md
  pkg/noderesources/allocatable.go
  pkg/noderesources/allocatable_test.go
  pkg/noderesources/resource_allocation.go
  test/integration/allocatable_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#55 Fix TestPodGroupClean
  pkg/coscheduling/coscheduling_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#52 Implementation of coscheduling based on CRD [Part 1]
  Makefile
  build/controller/Dockerfile
  build/scheduler/Dockerfile
  cmd/controller/app/options.go
  cmd/controller/app/server.go
  cmd/controller/controller.go
  cmd/scheduler/main.go
  cmd/scheduler/main_test.go
  go.mod
  go.sum
  hack/update-codegen.sh
  pkg/apis/podgroup/register.go
  pkg/apis/podgroup/v1alpha1/doc.go
  pkg/apis/podgroup/v1alpha1/register.go
  pkg/apis/podgroup/v1alpha1/types.go
  pkg/apis/podgroup/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/podgroup/v1alpha1/zz_generated.defaults.go
  pkg/controller/podgroup.go
  pkg/controller/podgroup_test.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/doc.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/doc.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/doc.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/podgroup/v1alpha1/doc.go
  pkg/generated/clientset/versioned/typed/podgroup/v1alpha1/fake/doc.go
  pkg/generated/clientset/versioned/typed/podgroup/v1alpha1/fake/fake_podgroup.go
  pkg/generated/clientset/versioned/typed/podgroup/v1alpha1/fake/fake_podgroup_client.go
  pkg/generated/clientset/versioned/typed/podgroup/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/podgroup/v1alpha1/podgroup.go
  pkg/generated/clientset/versioned/typed/podgroup/v1alpha1/podgroup_client.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/generated/informers/externalversions/podgroup/interface.go
  pkg/generated/informers/externalversions/podgroup/v1alpha1/interface.go
  pkg/generated/informers/externalversions/podgroup/v1alpha1/podgroup.go
  pkg/generated/listers/podgroup/v1alpha1/expansion_generated.go
  pkg/generated/listers/podgroup/v1alpha1/podgroup.go
  pkg/util/podgroup.go
  pkg/util/podgroup_test.go
  pkg/util/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#58 Rename MaxScheduleTime to ScheduleTimeoutSeconds
  kep/42-podgroup-coscheduling/README.md
  pkg/apis/podgroup/v1alpha1/types.go
  pkg/apis/podgroup/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/podgroup/v1alpha1/zz_generated.defaults.go
  pkg/controller/podgroup.go
  pkg/controller/podgroup_test.go
  pkg/util/podgroup.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#56 [Sample] Cross node preemption plugin
  Makefile
  cmd/scheduler/main.go
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
  pkg/crossnodepreemption/README.md
  pkg/crossnodepreemption/candidate.go
  pkg/crossnodepreemption/cross_node_preemption.go
  pkg/crossnodepreemption/cross_node_preemption_test.go
  test/integration/coscheduling_test.go
  test/integration/cross_node_preemption_test.go
  test/util/fake.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#65 Speed Up Docker Image Build Times
  Makefile
  build/controller/Dockerfile
  build/scheduler/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#64 Improve coscheduling's PodGroup cleanup
  pkg/coscheduling/coscheduling.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#66 Update "make clean" To Only Delete Specific Files
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS
