Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2020-04, with the labels that each got.

#2 KEP for co-scheduling plugin based on scheduler framework
  kep/20200116-lightweight-coscheduling-based-on-back-to-back-queue-sorting.md
  kep/20200116-lightweight-coscheduling-based-on-back-to-back-queue-sorting.png
Labels: approved, cncf-cla: yes, lgtm, sig/scheduling, size/L

#3 Sample QoS plugin
  .gitignore
  Makefile
  cmd/main.go
  go.mod
  go.sum
  hack/boilerplate/boilerplate.generatego.txt
  hack/install-etcd.sh
  hack/integration-test.sh
  hack/lib/etcd.sh
  hack/lib/golang.sh
  hack/lib/init.sh
  hack/lib/logging.sh
  hack/lib/util.sh
  hack/openapi-violation.list
  hack/unit-test.sh
  hack/update-generated-openapi.sh
  hack/update-gofmt.sh
  hack/update-vendor.sh
  hack/verify-gofmt.sh
  manifests/qos/scheduler-config.yaml
  pkg/qos/README.md
  pkg/qos/queuesort.go
  pkg/qos/queuesort_test.go
  test/integration/main_test.go
  test/integration/qos_test.go
  test/util/pod.go
  test/util/scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#6 fix broken link : https://git.k8s.io/community/contributors/guide/con…
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7 Add a Makefile default action
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S
