Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2020-10, with the labels that each got.

#67 Fix Automated Container Image Builds
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#60 Use concrete type in unversioned (internal) API fields
  pkg/apis/config/types.go
  pkg/apis/config/v1beta1/defaults.go
  pkg/apis/config/v1beta1/types.go
  pkg/apis/config/v1beta1/zz_generated.conversion.go
  pkg/apis/config/v1beta1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
  pkg/noderesources/allocatable.go
  pkg/noderesources/allocatable_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#68 Revert "Update "make clean" To Only Delete Specific Files"
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#69 Document Location For Controller Container Image
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#72 Fix the version number
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#74 Bump API deps to 1.18.9 in release-1.18
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#76 Fix Version Output For Automated Container Builds
  Makefile
  build/scheduler/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#77 Sync Build Automation From Master
  Makefile
  build/scheduler/Dockerfile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#79 Fix kubeconfig Options in cmd/controller
  cmd/controller/app/options.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#61 Trimaran: Real Load Aware Scheduling KEP
  kep/61-Trimaran-real-load-aware-scheduling/README.md
  kep/61-Trimaran-real-load-aware-scheduling/images/design.png
  kep/61-Trimaran-real-load-aware-scheduling/images/image1.png
  kep/61-Trimaran-real-load-aware-scheduling/images/image2.png
  kep/61-Trimaran-real-load-aware-scheduling/images/image3.png
  kep/61-Trimaran-real-load-aware-scheduling/images/image4.png
  kep/61-Trimaran-real-load-aware-scheduling/images/image5.png
  kep/61-Trimaran-real-load-aware-scheduling/images/image6.png
  kep/61-Trimaran-real-load-aware-scheduling/images/image7.png
  kep/61-Trimaran-real-load-aware-scheduling/images/image8.png
  kep/61-Trimaran-real-load-aware-scheduling/images/image9.png
  kep/61-Trimaran-real-load-aware-scheduling/images/safe-sched-graph.png
  kep/61-Trimaran-real-load-aware-scheduling/images/tlp-graph.png
  kep/61-Trimaran-real-load-aware-scheduling/kep.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#57 Implementation of coscheduling base on crd[Part 2]: coscheduling refactor-must have
  cmd/scheduler/main_test.go
  go.mod
  go.sum
  hack/integration-test.sh
  kep/42-podgroup-coscheduling/README.md
  manifests/coscheduling/crd.yaml
  manifests/coscheduling/scheduler-config.yaml
  pkg/apis/config/types.go
  pkg/apis/config/v1beta1/types.go
  pkg/apis/config/v1beta1/zz_generated.conversion.go
  pkg/controller/podgroup.go
  pkg/coscheduling/README.md
  pkg/coscheduling/core/core.go
  pkg/coscheduling/core/core_test.go
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
  pkg/util/constants.go
  pkg/util/podgroup.go
  test/integration/base.go
  test/integration/coscheduling_test.go
  test/util/aggregator.go
  test/util/apiserver.go
  test/util/extension.go
  test/util/fixtures.go
  test/util/scheduler.go
  test/util/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#87 Add reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
