Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2020-07, with the labels that each got.

#17 QoS QueueSort: rename files&plugin and fix a comment
  manifests/qos/scheduler-config.yaml
  pkg/qos/queue_sort.go
  pkg/qos/queue_sort_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#26 Temporary disable coscheduling integration test
  test/integration/coscheduling_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#22 simplify coscheduling unit test
  pkg/coscheduling/coscheduling_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#27 improve the current pod in accurary
  pkg/coscheduling/coscheduling.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#24 coscheduling: enhance PodGroupInfo and error check
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#30 remove unnecessary "else" in queue_sort.go
  pkg/qos/queue_sort.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#28 Mitigate the timeout of coscheduling integration test
  test/integration/coscheduling_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#15 update coscheduling stage to beta
  pkg/coscheduling/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
