Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2020-12, with the labels that each got.

#109 Implement resource pre-check
  pkg/coscheduling/core/core.go
  pkg/coscheduling/core/core_test.go
  pkg/coscheduling/coscheduling_test.go
  test/integration/coscheduling_test.go
  test/util/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#122 Fix case sensitive args
  manifests/capacityscheduling/scheduler-config.yaml
  manifests/noderesources/scheduler-config.yaml
  pkg/apis/config/v1beta1/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#124 Test cases for resource pre-check
  pkg/coscheduling/core/core.go
  test/integration/coscheduling_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#130 Add additionalProperties field for podgroup.minResources field
  manifests/coscheduling/crd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#128 Additional documentation for development purpose
  README.md
  doc/develop.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/L

#135 Fix wrong number of available cpus in README
  pkg/capacityscheduling/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#136 Update To Go 1.15.5
  build/controller/Dockerfile
  build/scheduler/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#134 Bugfix: cluster resource computation
  pkg/coscheduling/core/core.go
  pkg/coscheduling/core/core_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, size/M
