Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2020-11, with the labels that each got.

#92 Add comments on calculateBoundPods method
  pkg/coscheduling/core/core.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#93 coscheduling: cleanup and fixes
  pkg/coscheduling/core/core.go
  pkg/coscheduling/coscheduling.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#88 Prescheduling logic to controller
  pkg/controller/podgroup.go
  pkg/controller/podgroup_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#101 Fix flaky integration test
  test/integration/coscheduling_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#100 Add logs.InitLogs() to main program
  cmd/scheduler/main.go
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S

#105 Fix spec of CRD examples
  manifests/capacityscheduling/crd.yaml
  manifests/coscheduling/crd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#96 Cleanup and update Coscheduling parameters
  manifests/coscheduling/scheduler-config.yaml
  pkg/apis/config/types.go
  pkg/apis/config/v1beta1/defaults.go
  pkg/apis/config/v1beta1/types.go
  pkg/apis/config/v1beta1/zz_generated.conversion.go
  pkg/apis/config/v1beta1/zz_generated.deepcopy.go
  pkg/apis/config/v1beta1/zz_generated.defaults.go
  pkg/coscheduling/core/core.go
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#103 Add Pod State Scheduling Plugin
  cmd/scheduler/main.go
  cmd/scheduler/main_test.go
  pkg/podstate/README.md
  pkg/podstate/pod_state.go
  pkg/podstate/pod_state_test.go
  test/integration/pod_state_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XL

#107 Update README With Official Container Image Details
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#111 Update To Go 1.15.2
  build/controller/Dockerfile
  build/scheduler/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS
