Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2021-03, with the labels that each got.

#152 Add library support for Trimaran TargetLoadPacking plugin (Resolve issue #144)
  go.mod
  go.sum
  pkg/apis/config/types.go
  pkg/apis/config/v1beta1/types.go
  pkg/apis/config/v1beta1/zz_generated.conversion.go
  pkg/apis/config/v1beta1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/trimaran/targetloadpacking/README.md
  pkg/trimaran/targetloadpacking/targetloadpacking.go
  pkg/trimaran/targetloadpacking/targetloadpacking_test.go
  test/integration/targetloadpacking_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#153 Bump to Go 1.15.8
  build/controller/Dockerfile
  build/scheduler/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#157 Patch fixing a minor typo
  manifests/coscheduling/scheduler-config.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#133 Add Support For Container Image Multi-Arch Builds
  Makefile
  build/controller/Dockerfile
  build/scheduler/Dockerfile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#159 Revert "Simplify Multi Arch Build Targets"
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#160 add a install doc about released image
  README.md
  doc/install.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#158 Update the Design Details in README.md
  kep/48-node-resources-allocatable-scoring/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#162 Update Docs For v0.19.8 Release
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#164 go sum cleanup
  go.sum
  hack/openapi-violation.list
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#165 Update Docs For v0.19.8 Release
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#163 Update install doc to match release v0.19.8
  README.md
  doc/install.md
  manifests/coscheduling/scheduler-config.yaml
  manifests/install/all-in-one.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XL

#167 cherry-pick: update install doc to match release v0.19.8
  README.md
  doc/install.md
  manifests/coscheduling/scheduler-config.yaml
  manifests/install/all-in-one.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XL

#156 Add LoadVariationRiskBalancing plugin
  cmd/scheduler/main.go
  cmd/scheduler/main_test.go
  pkg/apis/config/register.go
  pkg/apis/config/types.go
  pkg/apis/config/v1beta1/defaults.go
  pkg/apis/config/v1beta1/register.go
  pkg/apis/config/v1beta1/types.go
  pkg/apis/config/v1beta1/zz_generated.conversion.go
  pkg/apis/config/v1beta1/zz_generated.deepcopy.go
  pkg/apis/config/v1beta1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/trimaran/README.md
  pkg/trimaran/docs/load-watcher-library.png
  pkg/trimaran/docs/load-watcher-service.png
  pkg/trimaran/loadvariationriskbalancing/README.md
  pkg/trimaran/loadvariationriskbalancing/analysis.go
  pkg/trimaran/loadvariationriskbalancing/analysis_test.go
  pkg/trimaran/loadvariationriskbalancing/collector.go
  pkg/trimaran/loadvariationriskbalancing/collector_test.go
  pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing.go
  pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing_test.go
  test/integration/loadVariationRiskBalancing_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XXL

#170 Add default value to pg status
  manifests/coscheduling/crd.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS
