Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2021-11, with the labels that each got.

#280 Trimaran: bug fixes for unpopulated watcher metrics
  pkg/apis/config/scheme/scheme_test.go
  pkg/apis/config/v1beta1/defaults.go
  pkg/apis/config/v1beta1/defaults_test.go
  pkg/trimaran/loadvariationriskbalancing/collector.go
  pkg/trimaran/targetloadpacking/targetloadpacking.go
Labels: ok-to-test, tide/merge-method-squash, cncf-cla: yes, approved, size/M, lgtm

#283 bump k8s deps to 1.21.6
  go.mod
  go.sum
Labels: size/L, cncf-cla: yes, approved, lgtm

#288 Fix a typo in a KEP directory name
  kep/217-resource-limit-aware-scoring/README.md
  kep/217-resource-limit-aware-scoring/kep.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#287 Bump 1.22
  build/controller/Dockerfile
  build/scheduler/Dockerfile
  cmd/scheduler/main_test.go
  go.mod
  go.sum
  hack/integration-test.sh
  hack/lib/etcd.sh
  hack/openapi-violation.list
  hack/testdata/127.0.0.1_10.0.0.1_kubernetes.default.svc-kubernetes.default-kubernetes-localhost.crt
  hack/testdata/127.0.0.1_10.0.0.1_kubernetes.default.svc-kubernetes.default-kubernetes-localhost.key
  hack/testdata/README.md
  hack/testdata/testdata
  pkg/apis/config/scheme/scheme_test.go
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/capacityscheduling/capacity_scheduling_test.go
  pkg/capacityscheduling/elasticquota.go
  pkg/coscheduling/core/core.go
  pkg/coscheduling/coscheduling.go
  pkg/crossnodepreemption/cross_node_preemption_test.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/noderesources/allocatable.go
  pkg/noderesources/resource_allocation.go
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/plugin.go
  pkg/noderesourcetopology/pluginhelpers.go
  pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing_test.go
  pkg/trimaran/targetloadpacking/targetloadpacking_test.go
  pkg/util/resource.go
  test/integration/allocatable_test.go
  test/integration/base.go
  test/integration/capacity_scheduling_test.go
  test/integration/coscheduling_test.go
  test/integration/cross_node_preemption_test.go
  test/integration/elasticquota_controller_test.go
  test/integration/loadVariationRiskBalancing_test.go
  test/integration/noderesourcetopology_test.go
  test/integration/pod_state_test.go
  test/integration/qos_test.go
  test/integration/targetloadpacking_test.go
  test/util/apiserver.go
  test/util/framework.go
  test/util/scheduler.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#286 update the documents to adapt to 0.21.X
  README.md
  doc/install.md
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: cncf-cla: yes, kind/documentation, approved, lgtm, size/S

#207 standardize error and state of return values of Permit
  pkg/coscheduling/core/core.go
  pkg/coscheduling/core/core_test.go
  pkg/coscheduling/coscheduling.go
  pkg/util/constants.go
Labels: size/L, cncf-cla: yes, approved, lgtm

#303 fix typo
  kep/9-capacity-scheduling/README.md
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/XS

#304 NodeResourceTopology: Update README with NRT CR dependency information
  pkg/noderesourcetopology/README.md
Labels: cncf-cla: yes, approved, lgtm, size/XS

#302 avoid instantiate core resource's informers
  pkg/coscheduling/coscheduling.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#305 images: use k8s-staging-test-infra/gcb-docker-gcloud
  cloudbuild.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS
