Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2021-07, with the labels that each got.

#208 rename master to main
  doc/release-guide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#197 Update Topology Aware Scheduling's KEP
  kep/119-node-resource-topology-aware-scheduling/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#209 up minAvailable to minMember in coscheduling
  pkg/coscheduling/README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#215 Add comments for NodeResourceTopologyMatchArgs
  pkg/apis/config/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#210 docs: add User Story in capacity-scheduling
  kep/9-capacity-scheduling/5.png
  kep/9-capacity-scheduling/6.png
  kep/9-capacity-scheduling/7.png
  kep/9-capacity-scheduling/8.png
  kep/9-capacity-scheduling/9.png
  kep/9-capacity-scheduling/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#217 KEP: Resource limit-aware scoring plugin
  kep/217-resource-limit-aware-scorcing/README.md
  kep/217-resource-limit-aware-scorcing/kep.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#218 add example config for podState plugin
  manifests/podstate/scheduler-config.yaml
  pkg/podstate/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S
