Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2021-04, with the labels that each got.

#173 Remove the unreserve config in installation doc
  doc/install.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#174 [1.19] Remove the unreserve config in installation doc
  doc/install.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#172 Bump To Go 1.15.10
  build/controller/Dockerfile
  build/scheduler/Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#179 bump deps to k8s 1.19.9
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#180 Automated cherry pick of #156: added LoadVariationRiskBalancing plugin (apis + docs) #143: NUMA aware scheduling #170: Add default value to pg status
  cmd/scheduler/main.go
  cmd/scheduler/main_test.go
  go.mod
  go.sum
  manifests/coscheduling/crd.yaml
  manifests/noderesourcetopology/cluster-role.yaml
  manifests/noderesourcetopology/crd.yaml
  manifests/noderesourcetopology/deploy.yaml
  manifests/noderesourcetopology/ns.yaml
  manifests/noderesourcetopology/scheduler-config.yaml
  manifests/noderesourcetopology/scheduler-configmap.yaml
  manifests/noderesourcetopology/test-deployment.yaml
  manifests/noderesourcetopology/worker-node-A.yaml
  manifests/noderesourcetopology/worker-node-B.yaml
  pkg/apis/config/register.go
  pkg/apis/config/types.go
  pkg/apis/config/v1beta1/defaults.go
  pkg/apis/config/v1beta1/register.go
  pkg/apis/config/v1beta1/types.go
  pkg/apis/config/v1beta1/zz_generated.conversion.go
  pkg/apis/config/v1beta1/zz_generated.deepcopy.go
  pkg/apis/config/v1beta1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/noderesourcetopology/README.md
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/filter_test.go
  pkg/noderesourcetopology/numa-topology.png
  pkg/trimaran/README.md
  pkg/trimaran/docs/load-watcher-library.png
  pkg/trimaran/docs/load-watcher-service.png
  pkg/trimaran/loadvariationriskbalancing/README.md
  pkg/trimaran/loadvariationriskbalancing/analysis.go
  pkg/trimaran/loadvariationriskbalancing/analysis_test.go
  pkg/trimaran/loadvariationriskbalancing/collector.go
  pkg/trimaran/loadvariationriskbalancing/collector_test.go
  pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing.go
  pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing_test.go
  test/integration/loadVariationRiskBalancing_test.go
  test/integration/noderesourcetopology_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#177 Bump 1.20
  cmd/scheduler/main_test.go
  go.mod
  go.sum
  hack/openapi-violation.list
  kep/2-lightweight-coscheduling/README.md
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/capacityscheduling/capacity_scheduling_test.go
  pkg/capacityscheduling/elasticquota.go
  pkg/capacityscheduling/elasticquota_test.go
  pkg/coscheduling/core/core.go
  pkg/coscheduling/core/core_test.go
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
  pkg/crossnodepreemption/cross_node_preemption.go
  pkg/crossnodepreemption/cross_node_preemption_test.go
  pkg/noderesources/allocatable.go
  pkg/noderesources/allocatable_test.go
  pkg/noderesources/resource_allocation.go
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/filter_test.go
  pkg/podstate/pod_state.go
  pkg/podstate/pod_state_test.go
  pkg/qos/queue_sort.go
  pkg/qos/queue_sort_test.go
  pkg/trimaran/loadvariationriskbalancing/analysis.go
  pkg/trimaran/loadvariationriskbalancing/analysis_test.go
  pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing.go
  pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing_test.go
  pkg/trimaran/targetloadpacking/targetloadpacking.go
  pkg/trimaran/targetloadpacking/targetloadpacking_test.go
  test/util/aggregator.go
  test/util/apiserver.go
  test/util/fake.go
  test/util/scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#181 Doc: update doc to fix couple of minor issues
  doc/install.md
  manifests/install/all-in-one.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#182 Update Compatibility Matrix For v0.19.9 Release
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#183 Doc: update doc to fix minor typo
  doc/install.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#185 Document List of Provided Plugins
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#187 docs: add args struct convention name
  doc/develop.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#190 Add PodState plugin test to main_test
  cmd/scheduler/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S
