Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2021-12, with the labels that each got.

#306 images: fix invalid k8s-staging-test-infra/gcb-docker-gcloud tag
  cloudbuild.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#307 coscheduling: PostFilter handles both Filter and PreFilter
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
Labels: ok-to-test, cncf-cla: yes, approved, size/M, lgtm

#298 0.21 chart should go with v1beta1
  manifests/install/charts/as-a-second-scheduler/templates/configmap.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#310 Nominate denkensk as an approver
  OWNERS
Labels: cncf-cla: yes, approved, lgtm, size/XS

#224 PreemptionToleration Plugin and its tests
  cmd/scheduler/main.go
  kep/205-preemption-toleration/README.md
  pkg/apis/config/register.go
  pkg/apis/config/scheme/scheme_test.go
  pkg/apis/config/types.go
  pkg/apis/config/v1beta2/defaults.go
  pkg/apis/config/v1beta2/defaults_test.go
  pkg/apis/config/v1beta2/register.go
  pkg/apis/config/v1beta2/types.go
  pkg/apis/config/v1beta2/zz_generated.conversion.go
  pkg/apis/config/v1beta2/zz_generated.deepcopy.go
  pkg/apis/config/v1beta2/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/preemptiontoleration/README.md
  pkg/preemptiontoleration/default_preeemption.go
  pkg/preemptiontoleration/preemption_toleration.go
  pkg/preemptiontoleration/preemption_toleration_policy.go
  pkg/preemptiontoleration/preemption_toleration_policy_test.go
  pkg/preemptiontoleration/preemption_toleration_test.go
  test/integration/preemption_toleration_test.go
Labels: kind/feature, ok-to-test, cncf-cla: yes, approved, lgtm, size/XXL

#308 Fix controller reconcile PodGroup status
  pkg/controller/podgroup.go
  pkg/controller/podgroup_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#313 Add PreemptionToleration to Plugin List in README
  README.md
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/XS
