Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2021-01, with the labels that each got.

#138 style: fix typo in capacity scheduling
  pkg/capacityscheduling/capacity_scheduling.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#126 Add PostFilter implementation
  cmd/scheduler/main_test.go
  pkg/coscheduling/core/core.go
  pkg/coscheduling/core/core_test.go
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
  test/integration/coscheduling_test.go
  test/util/fake.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#139 Fix PostBind group status update
  pkg/coscheduling/core/core.go
  pkg/coscheduling/core/core_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#115 Add TargetLoadPacking plugin
  cmd/scheduler/main.go
  cmd/scheduler/main_test.go
  go.mod
  go.sum
  manifests/trimaran/scheduler-config.yaml
  pkg/apis/config/register.go
  pkg/apis/config/types.go
  pkg/apis/config/v1beta1/defaults.go
  pkg/apis/config/v1beta1/register.go
  pkg/apis/config/v1beta1/types.go
  pkg/apis/config/v1beta1/zz_generated.conversion.go
  pkg/apis/config/v1beta1/zz_generated.deepcopy.go
  pkg/apis/config/v1beta1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/trimaran/handler.go
  pkg/trimaran/handler_test.go
  pkg/trimaran/targetloadpacking/README.md
  pkg/trimaran/targetloadpacking/targetloadpacking.go
  pkg/trimaran/targetloadpacking/targetloadpacking_test.go
  test/integration/targetloadpacking_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL
