Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2021-05, with the labels that each got.

#119 Topology aware scheduler plugin
  kep/119-node-resource-topology-aware-scheduling/README.md
  kep/119-node-resource-topology-aware-scheduling/kep.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#195 Fix nil pointer dereference logic
  pkg/util/podgroup.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#196 Refine coscheduling codes, set waittime to 0
  pkg/coscheduling/coscheduling.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#193 helm chart to install scheduler-plugins as a secondary scheduler
  doc/install.md
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/.helmignore
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/_helpers.tpl
  manifests/install/charts/as-a-second-scheduler/templates/configmap.yaml
  manifests/install/charts/as-a-second-scheduler/templates/crds/podgroup.yaml
  manifests/install/charts/as-a-second-scheduler/templates/deployment.yaml
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/templates/serviceaccount.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
