Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2021-09, with the labels that each got.

#247 Migrate to structured logging
  cmd/controller/app/server.go
  test/integration/base.go
  test/integration/capacity_scheduling_test.go
  test/integration/coscheduling_test.go
  test/integration/elasticquota_controller_test.go
  test/integration/noderesourcetopology_test.go
  test/util/aggregator.go
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/S

#235 Structured Logging migration: modify part logs of controller
  pkg/capacityscheduling/capacity_scheduling.go
Labels: kind/feature, ok-to-test, cncf-cla: yes, approved, size/M, lgtm

#246 Update coscheduling doc and add PostFilter
  doc/install.md
  kep/42-podgroup-coscheduling/README.md
  pkg/coscheduling/README.md
  pkg/coscheduling/coscheduling.go
Labels: cncf-cla: yes, kind/documentation, approved, kind/cleanup, lgtm, size/S

#243 Capacityscheduling doc
  kep/9-capacity-scheduling/README.md
Labels: ok-to-test, size/L, cncf-cla: yes, kind/documentation, approved, lgtm

#250 Migrate to Structured Logs in pkg/controller
  pkg/controller/elasticquota.go
  pkg/controller/elasticquota_test.go
  pkg/controller/podgroup.go
Labels: ok-to-test, cncf-cla: yes, approved, size/M, lgtm

#248 Fix podgroup controller UT issue
  pkg/controller/podgroup_test.go
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/S

#222 Add script to verify incorrect CRD yaml
  Makefile
  hack/verify-crdgen.sh
  manifests/capacityscheduling/crd.yaml
  manifests/coscheduling/crd.yaml
  manifests/crds/scheduling.sigs.k8s.io_elasticquotas.yaml
  manifests/crds/scheduling.sigs.k8s.io_podgroups.yaml
  manifests/crds/topology.node.k8s.io_noderesourcetopologies.yaml
  manifests/noderesourcetopology/crd.yaml
Labels: ok-to-test, size/L, cncf-cla: yes, approved, lgtm

#258 Move verify-crdgen as a standalone Makefile entry
  Makefile
  hack/verify-crdgen.sh
Labels: cncf-cla: yes, approved, lgtm, size/S, priority/critical-urgent

#259 Migrate noderesources and noderesourcetopology directories to structured logging
  pkg/noderesources/allocatable.go
  pkg/noderesources/resource_allocation.go
  pkg/noderesourcetopology/filter.go
Labels: ok-to-test, cncf-cla: yes, approved, size/M, lgtm

#256 noderesourcetopology: crosschecks NUMA node resources with node resources
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/plugin.go
Labels: ok-to-test, cncf-cla: yes, approved, size/M, lgtm

#262 Update load watcher dependency for Trimaran plugins
  go.mod
  go.sum
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/XS

#263 Ensure CRDs in the Helm Chart to be up-to-date
  manifests/install/charts/as-a-second-scheduler/templates/crds
  manifests/install/charts/as-a-second-scheduler/templates/crds/podgroup.yaml
Labels: cncf-cla: yes, approved, size/M, lgtm

#265 Improve UT: add api default test
  pkg/apis/config/v1beta1/defaults_test.go
  test/integration/capacity_scheduling_test.go
  test/integration/noderesourcetopology_test.go
Labels: ok-to-test, size/L, cncf-cla: yes, approved, lgtm
