Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2021-02, with the labels that each got.

#142 add a install doc about released image
  README.md
  doc/install.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/L

#149 bump deps to k8s 1.19.8
  go.mod
  go.sum
  pkg/trimaran/targetloadpacking/targetloadpacking_test.go
  test/util/fake.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#148 Fix PodGroup CRD definition has no status field schema
  manifests/coscheduling/crd.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
