Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2021-08, with the labels that each got.

#205 KEP: Preemption Toleration Plugin
  kep/205-preemption-toleration/README.md
  kep/205-preemption-toleration/kep.yaml
Labels: ok-to-test, size/L, cncf-cla: yes, approved, lgtm

#212 feat: add elastic quota controller
  cmd/controller/app/import_known_versions.go
  cmd/controller/app/server.go
  pkg/apis/scheduling/scheme/scheme.go
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/controller/elasticquota.go
  pkg/controller/elasticquota_test.go
  pkg/controller/podgroup.go
  test/integration/base.go
  test/integration/elasticquota_controller_test.go
  test/integration/loadVariationRiskBalancing_test.go
  test/integration/targetloadpacking_test.go
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/XXL

#228 bump k8s deps to 1.20.10
  go.mod
  go.sum
Labels: size/L, cncf-cla: yes, approved, lgtm

#230 update the documents to adapt to 0.20.X
  README.md
  doc/install.md
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: cncf-cla: yes, approved, size/M, lgtm

#226 Bump deps to k8s 1.21
  cmd/scheduler/main_test.go
  go.mod
  go.sum
  hack/openapi-violation.list
  kep/205-preemption-toleration/README.md
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/capacityscheduling/capacity_scheduling_test.go
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
  pkg/crossnodepreemption/cross_node_preemption.go
  pkg/crossnodepreemption/cross_node_preemption_test.go
  pkg/noderesources/allocatable_test.go
  pkg/noderesourcetopology/filter.go
  pkg/podstate/pod_state.go
  pkg/podstate/pod_state_test.go
  pkg/qos/queue_sort_test.go
  pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing_test.go
  pkg/trimaran/targetloadpacking/targetloadpacking_test.go
  pkg/util/parallelism.go
  test/integration/allocatable_test.go
  test/integration/capacity_scheduling_test.go
  test/integration/coscheduling_test.go
  test/integration/cross_node_preemption_test.go
  test/integration/loadVariationRiskBalancing_test.go
  test/integration/noderesourcetopology_test.go
  test/integration/pod_state_test.go
  test/integration/qos_test.go
  test/integration/targetloadpacking_test.go
  test/util/fake.go
  test/util/framework.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#234 update etcd script to not depend on ss or netstat
  hack/lib/etcd.sh
Labels: cncf-cla: yes, approved, lgtm, size/S

#220 Score Plugin for Topology Aware Scheduler
  cmd/scheduler/main_test.go
  go.mod
  go.sum
  manifests/noderesourcetopology/scheduler-config.yaml
  manifests/noderesourcetopology/scheduler-configmap.yaml
  pkg/apis/config/types.go
  pkg/apis/config/v1beta1/defaults.go
  pkg/apis/config/v1beta1/types.go
  pkg/apis/config/v1beta1/zz_generated.conversion.go
  pkg/apis/config/v1beta1/zz_generated.deepcopy.go
  pkg/apis/config/v1beta1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/noderesourcetopology/README.md
  pkg/noderesourcetopology/balanced_allocation.go
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/filter_test.go
  pkg/noderesourcetopology/least_allocated.go
  pkg/noderesourcetopology/most_allocated.go
  pkg/noderesourcetopology/plugin.go
  pkg/noderesourcetopology/pluginhelpers.go
  pkg/noderesourcetopology/score.go
  pkg/noderesourcetopology/score_test.go
  test/integration/noderesourcetopology_test.go
Labels: kind/feature, ok-to-test, cncf-cla: yes, approved, lgtm, size/XXL

#238 Fix access to null pointer
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/filter_test.go
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/S

#237 Add missing scheme_test.go
  go.mod
  pkg/apis/config/scheme/scheme_test.go
Labels: size/L, cncf-cla: yes, approved, kind/cleanup, lgtm

#245 Migrate to structured logging Part 2
  pkg/coscheduling/core/core.go
  pkg/coscheduling/coscheduling.go
  pkg/crossnodepreemption/cross_node_preemption.go
Labels: kind/feature, ok-to-test, cncf-cla: yes, approved, size/M, lgtm

#214 noderesourcetopology: Use Quantity in ResourceInfo
  go.mod
  go.sum
  manifests/noderesourcetopology/crd.yaml
  pkg/noderesourcetopology/filter_test.go
  pkg/noderesourcetopology/pluginhelpers.go
  pkg/noderesourcetopology/score_test.go
  test/integration/noderesourcetopology_test.go
Labels: ok-to-test, size/L, tide/merge-method-squash, cncf-cla: yes, approved, lgtm
