Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2022-01, with the labels that each got.

#272 install: create a RoleBinding for obtain delegated authentication
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#318 NodeResourceTopology: handle best-effort pods in score plugin
  pkg/noderesourcetopology/score.go
  test/integration/noderesourcetopology_test.go
Labels: ok-to-test, cncf-cla: yes, approved, size/M, lgtm

#323 move PodGroup label to pkg/api
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/controller/podgroup.go
  pkg/controller/podgroup_test.go
  pkg/coscheduling/core/core.go
  pkg/coscheduling/core/core_test.go
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
  pkg/util/constants.go
  pkg/util/podgroup.go
  test/integration/coscheduling_test.go
Labels: size/L, cncf-cla: yes, approved, lgtm

#324 cherry pick move podgroup key to api in v1.19
  cmd/controller/app/server.go
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/controller/podgroup.go
  pkg/controller/podgroup_test.go
  pkg/coscheduling/core/core.go
  pkg/coscheduling/core/core_test.go
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
  pkg/util/constants.go
  pkg/util/podgroup.go
  test/integration/coscheduling_test.go
Labels: size/L, cncf-cla: yes, approved, lgtm

#317 register custom resource events for efficient pod enqueuing
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/coscheduling/coscheduling.go
  pkg/noderesourcetopology/plugin.go
Labels: cncf-cla: yes, approved, lgtm, size/S
