Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2022-12, with the labels that each got.

#399 add sysched design KEP
  kep/399-sysched-scoring/README.md
  kep/399-sysched-scoring/images/arch.png
  kep/399-sysched-scoring/images/example_complete.png
  kep/399-sysched-scoring/images/exs.png
  kep/399-sysched-scoring/images/sched4sec_attacksrf.png
  kep/399-sysched-scoring/kep.yaml
Labels: kind/feature, ok-to-test, size/L, tide/merge-method-squash, cncf-cla: yes, approved, lgtm, release-note-none

#437 Add local cache for noderesourcetopology using the reserve plugin [2/3] - implementation
  Makefile
  go.mod
  go.sum
  pkg/noderesourcetopology/cache/cache.go
  pkg/noderesourcetopology/cache/indexer.go
  pkg/noderesourcetopology/cache/indexer_test.go
  pkg/noderesourcetopology/cache/overreserve.go
  pkg/noderesourcetopology/cache/overreserve_test.go
  pkg/noderesourcetopology/cache/passthrough.go
  pkg/noderesourcetopology/cache/store.go
  pkg/noderesourcetopology/cache/store_test.go
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/plugin.go
  pkg/noderesourcetopology/pluginhelpers.go
  pkg/noderesourcetopology/score.go
  pkg/noderesourcetopology/stringify/stringify.go
  pkg/noderesourcetopology/stringify/stringify_test.go
  test/integration/noderesourcetopology_cache_test.go
  test/integration/noderesourcetopology_test.go
  test/integration/nrtutils.go
  test/util/utils.go
  vendor/github.com/OneOfOne/xxhash/.gitignore
  vendor/github.com/OneOfOne/xxhash/.travis.yml
  vendor/github.com/OneOfOne/xxhash/LICENSE
  vendor/github.com/OneOfOne/xxhash/README.md
  vendor/github.com/OneOfOne/xxhash/xxhash.go
  vendor/github.com/OneOfOne/xxhash/xxhash_go17.go
  vendor/github.com/OneOfOne/xxhash/xxhash_safe.go
  vendor/github.com/OneOfOne/xxhash/xxhash_unsafe.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/null.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/k8stopologyawareschedwg/podfingerprint/LICENSE
  vendor/github.com/k8stopologyawareschedwg/podfingerprint/README.md
  vendor/github.com/k8stopologyawareschedwg/podfingerprint/podfingerprint.go
  vendor/github.com/k8stopologyawareschedwg/podfingerprint/tracing.go
  vendor/modules.txt
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/XXL, release-note-none

#460 topologysort integrationtest update
  test/integration/topologicalsort_test.go
Labels: ok-to-test, size/L, cncf-cla: yes, approved, lgtm, release-note-none

#459 bump controller-gen to v0.9.2
  .github/PULL_REQUEST_TEMPLATE.md
  apis/scheduling/v1alpha1/types.go
  hack/verify-crdgen.sh
  manifests/appgroup/crd.yaml
  manifests/capacityscheduling/crd.yaml
  manifests/coscheduling/crd.yaml
  manifests/networktopology/crd.yaml
  manifests/noderesourcetopology/crd.yaml
  pkg/controller/elasticquota.go
  pkg/controller/podgroup.go
Labels: cncf-cla: yes, approved, size/M, kind/cleanup, lgtm, release-note-none

#468 cleanup: remove ioutil for new go version
  cmd/scheduler/main_test.go
Labels: ok-to-test, cncf-cla: yes, approved, size/M, kind/cleanup, lgtm, release-note-none

#463 Documents update for release v0.24.9
  Makefile
  README.md
  doc/develop.md
  doc/install.md
  hack/.notableofcontents
  hack/update-toc.sh
  hack/verify-toc.sh
  kep/119-node-resource-topology-aware-scheduling/README.md
  kep/2-lightweight-coscheduling/README.md
  kep/205-preemption-toleration/README.md
  kep/217-resource-limit-aware-scoring/README.md
  kep/260-network-aware-scheduling/README.md
  kep/399-sysched-scoring/README.md
  kep/42-podgroup-coscheduling/README.md
  kep/48-node-resources-allocatable-scoring/README.md
  kep/61-Trimaran-real-load-aware-scheduling/README.md
  kep/9-capacity-scheduling/README.md
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: size/XL, cncf-cla: yes, kind/documentation, approved, release-note-none

#464 Automated cherry pick of #463: Documents update for release v0.24.9
  Makefile
  README.md
  doc/develop.md
  doc/install.md
  hack/.notableofcontents
  hack/update-toc.sh
  hack/verify-toc.sh
  kep/119-node-resource-topology-aware-scheduling/README.md
  kep/2-lightweight-coscheduling/README.md
  kep/205-preemption-toleration/README.md
  kep/217-resource-limit-aware-scoring/README.md
  kep/260-network-aware-scheduling/README.md
  kep/399-sysched-scoring/README.md
  kep/42-podgroup-coscheduling/README.md
  kep/48-node-resources-allocatable-scoring/README.md
  kep/61-Trimaran-real-load-aware-scheduling/README.md
  kep/9-capacity-scheduling/README.md
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: size/XL, cncf-cla: yes, approved, release-note-none

#469 cleanup: gofmt: mechanical changes for gofmt 1.19
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/controller/elasticquota.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/preemptiontoleration/preemption_toleration_policy.go
Labels: cncf-cla: yes, approved, size/M, kind/cleanup, lgtm, release-note-none

#455 integration tests for the NodeResourceTopology cache and resync loop
  test/integration/noderesourcetopology_cache_test.go
  test/integration/nrtutils.go
Labels: size/L, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none
