Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2022-06, with the labels that each got.

#381 fix: consider only nominated pods of same namespace in preemption
  pkg/capacityscheduling/capacity_scheduling.go
Labels: kind/bug, ok-to-test, cncf-cla: yes, approved, lgtm, size/XS, release-note-none

#385 Minor fix for coscheduling plugin's PostBind logic
  pkg/coscheduling/core/core.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS, release-note-none

#382 Explain a downside of running multiple schedulers
  doc/install.md
Labels: ok-to-test, tide/merge-method-squash, cncf-cla: yes, kind/documentation, approved, lgtm, size/S, release-note-none

#384 fix bugs of score calculation formula in TargetLoadPacking Plugin
  kep/61-Trimaran-real-load-aware-scheduling/README.md
  pkg/trimaran/targetloadpacking/targetloadpacking.go
  pkg/trimaran/targetloadpacking/targetloadpacking_test.go
Labels: kind/bug, ok-to-test, tide/merge-method-squash, cncf-cla: yes, approved, lgtm, size/XS, release-note-none

#373 noderesourcetopology: quicker and simpler fail logic for filter when dealing with node-level resources
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/filter_test.go
  pkg/noderesourcetopology/pluginhelpers.go
Labels: ok-to-test, tide/merge-method-squash, cncf-cla: yes, approved, size/M, kind/cleanup, lgtm, release-note-none

#390 Replace hard coded time duration by config param in coscheduling
  pkg/coscheduling/core/core.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS, release-note-none

#371 noderesourcetopology: fix filter plugin resource alignment when scope=container
  pkg/noderesourcetopology/TESTS.md
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/filter_test.go
Labels: kind/bug, ok-to-test, size/XL, cncf-cla: yes, approved, lgtm, release-note-none

#372 noderesourcetopology: fix handling of non-NUMA-affine resources
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/filter_test.go
Labels: kind/bug, ok-to-test, size/L, cncf-cla: yes, approved, lgtm, release-note-none

#395 Update From Alpine 3.12 to 3.16
  build/controller/Dockerfile
  build/scheduler/Dockerfile
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS, release-note-none

#383 Added Readme for helm
  doc/install.md
  manifests/install/charts/as-a-second-scheduler/README.md
Labels: ok-to-test, tide/merge-method-squash, cncf-cla: yes, kind/documentation, approved, size/M, lgtm, release-note-none
