Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2022-02, with the labels that each got.

#291 NodeResourceTopology scheduler plugin cleanup
  manifests/noderesourcetopology/deploy.yaml
  manifests/noderesourcetopology/test-deployment.yaml
  pkg/noderesourcetopology/README.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#319 cleanup: "allocable" -> "allocated" to adapt to upstream naming convension
  pkg/noderesourcetopology/README.md
  test/integration/noderesourcetopology_test.go
Labels: cncf-cla: yes, approved, size/M, lgtm

#312 fix bugs of resource calculation in node resource topology
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/score.go
  pkg/util/resource.go
  pkg/util/resource_test.go
Labels: kind/bug, ok-to-test, size/L, cncf-cla: yes, approved, lgtm

#328 bump k8s deps to 1.22.6
  cmd/scheduler/main_test.go
  go.mod
  go.sum
  pkg/noderesources/resource_allocation.go
Labels: size/L, cncf-cla: yes, approved, lgtm

#329 missing capacitySchedulingConfig config test
  cmd/scheduler/main_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#326 enhancement: improve the helm chart implementation to configure multi plugins
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/templates/configmap.yaml
  manifests/install/charts/as-a-second-scheduler/templates/deployment.yaml
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: ok-to-test, size/L, cncf-cla: yes, approved, lgtm

#332 update the documents to adapt to 0.22.6
  README.md
  doc/install.md
  manifests/install/all-in-one.yaml
Labels: cncf-cla: yes, approved, size/M, lgtm

#333 Add a simple Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, approved, size/M, lgtm

#336 Add `go:build` directive in tools.go
  hack/tools.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS

#335 Move doc/release-guide.md to RELEASE.md
  RELEASE.md
  doc/release-guide.md
Labels: size/L, cncf-cla: yes, kind/documentation, approved, kind/cleanup, lgtm

#338 bump go version to 1.17 in Dockerfiles
  build/controller/Dockerfile
  build/scheduler/Dockerfile
Labels: cncf-cla: yes, approved, kind/failing-test, lgtm, size/XS
