Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2022-08, with the labels that each got.

#403 Trimaran: Restructure for ease of adding trimaran plugins
  apis/config/scheme/scheme_test.go
  apis/config/types.go
  apis/config/v1beta2/zz_generated.conversion.go
  apis/config/v1beta3/defaults.go
  apis/config/v1beta3/defaults_test.go
  apis/config/v1beta3/types.go
  apis/config/v1beta3/zz_generated.conversion.go
  apis/config/v1beta3/zz_generated.deepcopy.go
  apis/config/zz_generated.deepcopy.go
  pkg/trimaran/collector.go
  pkg/trimaran/collector_test.go
  pkg/trimaran/handler.go
  pkg/trimaran/handler_test.go
  pkg/trimaran/loadvariationriskbalancing/analysis.go
  pkg/trimaran/loadvariationriskbalancing/analysis_test.go
  pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing.go
  pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing_test.go
  pkg/trimaran/resourcestats.go
  pkg/trimaran/resourcestats_test.go
  pkg/trimaran/targetloadpacking/targetloadpacking.go
  pkg/trimaran/targetloadpacking/targetloadpacking_test.go
  test/integration/loadVariationRiskBalancing_test.go
  test/integration/targetloadpacking_test.go
Labels: ok-to-test, tide/merge-method-squash, cncf-cla: yes, approved, kind/cleanup, lgtm, size/XXL, release-note-none

#401 LoadVariationRiskBalancing: enhanced integration test
  test/integration/loadVariationRiskBalancing_test.go
Labels: ok-to-test, tide/merge-method-squash, cncf-cla: yes, approved, size/M, kind/cleanup, lgtm, release-note-none

#413 [release-0.23] bump k8s deps to v1.23.10
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/server/options/audit.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/client-go/tools/clientcmd/auth_loaders.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/preemption/preemption.go
  vendor/modules.txt
Labels: size/L, cncf-cla: yes, approved, lgtm, release-note-none

#414 updated docs for v0.23.10 release
  README.md
  doc/install.md
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/configmap.yaml
  manifests/install/charts/as-a-second-scheduler/templates/deployment.yaml
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/templates/serviceaccount.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: size/L, tide/merge-method-squash, cncf-cla: yes, kind/documentation, approved, lgtm, release-note-none

#417 Automated cherry pick of #414: updated docs for v0.23.10 release
  README.md
  doc/install.md
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/configmap.yaml
  manifests/install/charts/as-a-second-scheduler/templates/deployment.yaml
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/templates/serviceaccount.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: size/L, cncf-cla: yes, approved, lgtm, release-note-none
