Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2023-08, with the labels that each got.

#609 fix 404 link of `Kubeadam`
  doc/install.md
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/XS, release-note-none

#610 test: fix channel leak in event broadcaster
  test/integration/utils.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS, release-note-none

#611 build: bump builder image to go 1.20
  build/controller/Dockerfile
  build/scheduler/Dockerfile
Labels: cncf-cla: yes, approved, release-note, lgtm, size/XS

#623 Find correct cost associated with given NUMA node ID
  pkg/noderesourcetopology/least_numa.go
  pkg/noderesourcetopology/least_numa_test.go
Labels: kind/bug, size/L, cncf-cla: yes, approved, release-note, lgtm

#627 Find correct combination with given NUMA node ID
  pkg/noderesourcetopology/least_numa.go
  pkg/noderesourcetopology/least_numa_test.go
Labels: kind/bug, ok-to-test, size/L, cncf-cla: yes, approved, release-note, lgtm

#630 rename hugo config to config.yaml
  site/config.yaml
Labels: cncf-cla: yes, kind/documentation, approved, lgtm, size/XS, release-note-none
