Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2023-01, with the labels that each got.

#472 Automated cherry pick of #470: update the controller image in all-in-one.yaml
  manifests/install/all-in-one.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS, release-note-none

#471 update rbac to allow all verbs for podgroups/status
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/XS, release-note-none

#454 Add LeastNUMANodes ScoringStrategy for NodeResourceTopologyMatch plugin
  kep/454-numa-nodes-scoring/README.md
  kep/454-numa-nodes-scoring/kep.yaml
Labels: kind/feature, ok-to-test, size/L, cncf-cla: yes, approved, lgtm, release-note-none

#473 Automated cherry pick of #471: update rbac to allow all verbs for podgroups/status
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS, release-note-none

#480 Automated cherry pick of #477: Clean up manifests for all-in-one installation
  doc/install.md
  manifests/install/all-in-one.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS, release-note-none

#479 Revisit hack/verify-crdgen.sh
  apis/scheduling/v1alpha1/types.go
  hack/verify-crdgen.sh
  manifests/appgroup/crd.yaml
  manifests/capacityscheduling/crd.yaml
  manifests/coscheduling/crd.yaml
  manifests/networktopology/crd.yaml
  manifests/noderesourcetopology/crd.yaml
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/S, release-note-none

#478 Optimize descriptions in the document
  README.md
  doc/develop.md
  pkg/networkaware/README.md
  pkg/noderesourcetopology/README.md
  pkg/qos/README.md
Labels: cncf-cla: yes, kind/documentation, approved, lgtm, size/S, release-note-none

#482 Add goreportcard and license badges to README
  README.md
Labels: cncf-cla: yes, kind/documentation, approved, lgtm, size/XS, release-note-none

#483 noderesourcetopologies: address pending minor cleanups
  apis/config/v1beta2/types.go
  apis/config/v1beta3/types.go
  pkg/noderesourcetopology/cache/store.go
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/pluginhelpers.go
  pkg/noderesourcetopology/score.go
Labels: tide/merge-method-squash, cncf-cla: yes, approved, size/M, kind/cleanup, lgtm, release-note-none

#487 Update noderesourcetopology README.md with information about scoringStrategies
  pkg/noderesourcetopology/README.md
Labels: ok-to-test, cncf-cla: yes, kind/documentation, approved, lgtm, size/S, release-note-none

#484 Update NUMA nodes scoring KEP to consider zone distance when scoring
  kep/454-numa-nodes-scoring/README.md
  kep/454-numa-nodes-scoring/kep.yaml
Labels: kind/feature, ok-to-test, cncf-cla: yes, approved, size/M, lgtm, release-note-none

#490 ensure plugins implement the interface
  pkg/networkaware/topologicalsort/topologicalsort.go
  pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing.go
  pkg/trimaran/targetloadpacking/targetloadpacking.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS, release-note-none
