Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2023-04, with the labels that each got.

#565 fix etcd install hint info.
  hack/install-etcd.sh
  hack/lib/etcd.sh
Labels: ok-to-test, size/L, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none

#544 ElasticQuota: add unit test for PostFilter & PodEligibleToPreemptOthers
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/capacityscheduling/capacity_scheduling_test.go
Labels: ok-to-test, size/L, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none

#549 Coscheduling: integration-test for PodGroup status
  pkg/controllers/podgroup_controller.go
  test/integration/coscheduling_test.go
  test/integration/elasticquota_controller_test.go
  test/integration/podgroup_controller_test.go
  test/integration/utils.go
  test/util/utils.go
Labels: kind/bug, kind/feature, ok-to-test, size/L, cncf-cla: yes, approved, lgtm, release-note-none

#569 Delete Useless options in controller
  cmd/controller/app/options.go
  cmd/controller/app/server.go
  pkg/controllers/elasticquota_controller.go
  pkg/controllers/podgroup_controller.go
Labels: ok-to-test, size/L, cncf-cla: yes, approved, kind/cleanup, release-note, lgtm

#572 Create bug-report template in GitHub form
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: cncf-cla: yes, approved, size/M, lgtm, release-note-none

#570 chart: fix service account name
  manifests/install/charts/as-a-second-scheduler/templates/deployment.yaml
Labels: kind/feature, ok-to-test, cncf-cla: yes, approved, lgtm, size/XS, release-note-none, area/helm

#580 nrt: overreserve: minimize the pod listings
  pkg/noderesourcetopology/cache/overreserve.go
  pkg/noderesourcetopology/cache/overreserve_test.go
  pkg/noderesourcetopology/cache/store.go
  pkg/noderesourcetopology/cache/store_test.go
Labels: size/L, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none
