Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2023-07, with the labels that each got.

#574 Coscheduling: remove podgroup.scheduled
  apis/scheduling/v1alpha1/types.go
  config/crd/bases/scheduling.x-k8s.io_podgroups.yaml
  kep/42-podgroup-coscheduling/README.md
  manifests/coscheduling/crd.yaml
  pkg/controllers/podgroup_controller.go
  pkg/controllers/podgroup_controller_test.go
  pkg/coscheduling/README.md
  test/integration/podgroup_controller_test.go
  test/util/utils.go
Labels: kind/bug, ok-to-test, size/L, tide/merge-method-squash, cncf-cla: yes, approved, kind/cleanup, release-note, lgtm, kind/api-change

#602 Change Node Role to control-plane in Developer Guide
  doc/develop.md
Labels: ok-to-test, cncf-cla: yes, kind/documentation, approved, lgtm, size/XS, release-note-none

#559 add podGroup backoff time for coscheduling
  apis/config/scheme/scheme_test.go
  apis/config/types.go
  apis/config/v1/defaults.go
  apis/config/v1/defaults_test.go
  apis/config/v1/types.go
  apis/config/v1/zz_generated.conversion.go
  apis/config/v1/zz_generated.deepcopy.go
  apis/config/v1beta2/defaults.go
  apis/config/v1beta2/defaults_test.go
  apis/config/v1beta2/types.go
  apis/config/v1beta2/zz_generated.conversion.go
  apis/config/v1beta2/zz_generated.deepcopy.go
  apis/config/v1beta3/defaults.go
  apis/config/v1beta3/defaults_test.go
  apis/config/v1beta3/types.go
  apis/config/v1beta3/zz_generated.conversion.go
  apis/config/v1beta3/zz_generated.deepcopy.go
  pkg/coscheduling/core/core.go
  pkg/coscheduling/core/core_test.go
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
  test/integration/coscheduling_test.go
Labels: ok-to-test, size/L, cncf-cla: yes, approved, release-note, lgtm

#604 Documents update for release v0.26.7
  README.md
  doc/install.md
  manifests/appgroup/deploy-sig-scheduling-controller-and-scheduler.yaml
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/configmap.yaml
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
  manifests/networktopology/deploy-sig-scheduling-controller-and-scheduler.yaml
  pkg/networkaware/README.md
Labels: cncf-cla: yes, kind/documentation, approved, size/M, lgtm, release-note-none

#605 Automated cherry pick of #604: Documents update for release v0.26.7
  README.md
  doc/install.md
  manifests/appgroup/deploy-sig-scheduling-controller-and-scheduler.yaml
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/configmap.yaml
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
  manifests/networktopology/deploy-sig-scheduling-controller-and-scheduler.yaml
  pkg/networkaware/README.md
Labels: cncf-cla: yes, approved, size/M, lgtm, release-note-none
