Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2023-09, with the labels that each got.

#612 Trimaran minor bug fixes
  pkg/trimaran/collector.go
  pkg/trimaran/collector_test.go
  pkg/trimaran/resourcestats.go
  pkg/trimaran/resourcestats_test.go
Labels: ok-to-test, size/L, cncf-cla: yes, approved, kind/cleanup, release-note, lgtm

#634 docs: update 1.25 target kubernetes version to 1.25.12
  README.md
  site/content/en/_index.md
Labels: cncf-cla: yes, kind/documentation, approved, lgtm, size/XS, release-note-none

#633 doc: upgrade docs to v0.25.12
  README.md
  doc/install.md
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: cncf-cla: yes, kind/documentation, approved, size/M, lgtm, release-note-none

#638 fix outdate url
  doc/install.md
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/XS, release-note-none
