Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2023-03, with the labels that each got.

#528 switch API group to x-k8s.io for network-aware CRDs and plugins
  go.mod
  go.sum
  kep/260-network-aware-scheduling/README.md
  manifests/appgroup/appgroup-controller-deployment.yaml
  manifests/appgroup/cluster-role.yaml
  manifests/appgroup/crd.yaml
  manifests/appgroup/example.yaml
  manifests/appgroup/onlineBoutique-appGroup-example.yaml
  manifests/appgroup/redis-appGroup-example.yaml
  manifests/crds/appgroup.diktyo.x-k8s.io_appgroups.yaml
  manifests/crds/networktopology.diktyo.x-k8s.io_networktopologies.yaml
  manifests/networktopology/cluster-role.yaml
  manifests/networktopology/crd.yaml
  manifests/networktopology/example.yaml
  manifests/networktopology/networktopology-controller-deployment.yaml
  vendor/github.com/diktyo-io/appgroup-api/pkg/apis/appgroup/register.go
  vendor/github.com/diktyo-io/networktopology-api/pkg/apis/networktopology/register.go
  vendor/modules.txt
Labels: ok-to-test, cncf-cla: yes, approved, size/M, lgtm, kind/api-change, release-note-action-required

#512 Introduce pluginargs validation for NodeResourceTopologyMatch plugin
  apis/config/validation/validation_pluginargs.go
  apis/config/validation/validation_plugingargs_test.go
  pkg/noderesourcetopology/plugin.go
  test/integration/noderesourcetopology_test.go
Labels: kind/feature, ok-to-test, size/L, cncf-cla: yes, approved, lgtm, release-note-none

#517 install: move crds folder to chart root folder
  manifests/install/charts/as-a-second-scheduler/crds
  manifests/install/charts/as-a-second-scheduler/templates/crds
Labels: ok-to-test, cncf-cla: yes, approved, release-note, lgtm, size/XS

#499 Clean up to use `nil` as the context argument
  pkg/capacityscheduling/capacity_scheduling_test.go
  pkg/networkaware/networkoverhead/networkoverhead_test.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/S, release-note-none

#511 Fix scheduler metrics
  cmd/scheduler/main.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/leaderelection/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/restclient/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/version/metrics.go
  vendor/modules.txt
Labels: kind/bug, ok-to-test, size/L, cncf-cla: yes, approved, release-note, lgtm

#519 chart: use release.namespace to specify target ns
  manifests/install/charts/as-a-second-scheduler/templates/configmap.yaml
  manifests/install/charts/as-a-second-scheduler/templates/deployment.yaml
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/templates/serviceaccount.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: ok-to-test, cncf-cla: yes, approved, size/M, release-note, lgtm

#530 Fix an issue arm64 image is not built properly
  Makefile
Labels: cncf-cla: yes, approved, lgtm, size/XS, release-note-none, kind/regression

#521 feat: update PodGroup label key
  apis/scheduling/v1alpha1/types.go
  doc/install.md
  pkg/controllers/podgroup_test.go
  pkg/coscheduling/README.md
  pkg/coscheduling/core/core.go
  pkg/coscheduling/coscheduling.go
  pkg/util/podgroup.go
Labels: kind/feature, ok-to-test, cncf-cla: yes, approved, release-note, lgtm, size/S

#535 fix: update develop.md
  doc/develop.md
Labels: ok-to-test, cncf-cla: yes, kind/documentation, approved, lgtm, size/XS, release-note-none

#538 Replace k8s.gcr.io with registry.k8s.io
  Makefile
  doc/install.md
Labels: cncf-cla: yes, approved, kind/cleanup, release-note, lgtm, size/S

#532 doc.go modifications in diktyo.io projects
  go.mod
  go.sum
  vendor/github.com/diktyo-io/appgroup-api/pkg/apis/appgroup/v1alpha1/doc.go
  vendor/github.com/diktyo-io/networktopology-api/pkg/apis/networktopology/v1alpha1/doc.go
  vendor/modules.txt
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/S, release-note-none

#541 Documents update for release v0.25.7
  README.md
  doc/install.md
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: cncf-cla: yes, kind/documentation, approved, size/M, lgtm, release-note-none

#542 Automated cherry pick of #541: Documents update for release v0.25.7
  README.md
  doc/install.md
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: cncf-cla: yes, kind/documentation, approved, size/M, lgtm, release-note-none

#529 update OWNERS
  OWNERS
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/S, release-note-none

#548 bump k8s deps to v1.26.3
  go.mod
  go.sum
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/interface.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/parallelize/parallelism.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/binder.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/runtime/framework.go
  vendor/k8s.io/kubernetes/pkg/scheduler/internal/queue/scheduling_queue.go
  vendor/k8s.io/kubernetes/pkg/scheduler/scheduler.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/conn.go
Labels: size/XL, cncf-cla: yes, approved, lgtm, release-note-none

#504 Add new NRT cache type DiscardReservedNodes
  apis/config/types.go
  apis/config/v1/types.go
  apis/config/v1/zz_generated.conversion.go
  apis/config/v1beta2/types.go
  apis/config/v1beta2/zz_generated.conversion.go
  apis/config/v1beta3/types.go
  apis/config/v1beta3/zz_generated.conversion.go
  pkg/noderesourcetopology/cache/cache.go
  pkg/noderesourcetopology/cache/discardreserved.go
  pkg/noderesourcetopology/cache/discardreserved_test.go
  pkg/noderesourcetopology/cache/overreserve.go
  pkg/noderesourcetopology/cache/passthrough.go
  pkg/noderesourcetopology/plugin.go
  pkg/noderesourcetopology/postbind.go
Labels: kind/feature, ok-to-test, size/L, cncf-cla: yes, approved, release-note, lgtm

#545 doc: update ElasticQuota's max value
  kep/9-capacity-scheduling/README.md
Labels: ok-to-test, cncf-cla: yes, kind/documentation, approved, lgtm, size/XS, release-note-none

#551 Add integration test args to Makefile
  Makefile
  hack/integration-test.sh
Labels: kind/feature, ok-to-test, cncf-cla: yes, approved, lgtm, size/XS, release-note-none, area/makefile

#547 nrt: filter: enable to coalesce log filter reason
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/filter_test.go
  test/integration/noderesourcetopology_test.go
Labels: cncf-cla: yes, approved, size/M, kind/cleanup, lgtm, release-note-none

#550 nodetopologymatch: bump deps
  go.mod
  go.sum
  pkg/noderesourcetopology/cache/store.go
  test/integration/noderesourcetopology_cache_test.go
  vendor/github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha2/helper/attribute/attribute.go
  vendor/github.com/k8stopologyawareschedwg/podfingerprint/tracing.go
  vendor/modules.txt
Labels: size/L, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none

#553 build: fallback version to based on date if no tags found
  Makefile
Labels: cncf-cla: yes, approved, lgtm, size/XS, release-note-none

#554 Cleanup PostBind in coscheduling
  cmd/scheduler/main_test.go
  pkg/controllers/podgroup_test.go
  pkg/coscheduling/core/core.go
  pkg/coscheduling/core/core_test.go
  pkg/coscheduling/coscheduling.go
  test/integration/coscheduling_test.go
Labels: ok-to-test, size/L, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none

#555 Upgrade the controller image version of all-in-one.yaml
  manifests/install/all-in-one.yaml
Labels: kind/bug, cncf-cla: yes, approved, release-note, lgtm, size/XS

#557 nrt: overreserve: drop custom indexer, use lister
  pkg/noderesourcetopology/cache/indexer.go
  pkg/noderesourcetopology/cache/indexer_test.go
  pkg/noderesourcetopology/cache/overreserve.go
  pkg/noderesourcetopology/cache/overreserve_test.go
  pkg/noderesourcetopology/cache/store.go
  pkg/noderesourcetopology/pluginhelpers.go
  test/integration/noderesourcetopology_cache_test.go
Labels: size/XL, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none

#556 Cherry pick: Upgrade the controller image version of the all-in-one.yaml
  manifests/install/all-in-one.yaml
Labels: kind/bug, cncf-cla: yes, approved, release-note, lgtm, size/XS

#527 feat: migrate elasticquota controller to ctrl runtime
  cmd/controller/app/server.go
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  pkg/controller/elasticquota.go
  pkg/controllers/CapacityScheduling/elasticquota_controller.go
  pkg/controllers/elasticquota_controller.go
  pkg/controllers/elasticquota_controller_test.go
  pkg/controllers/podgroup_controller.go
  pkg/controllers/podgroup_controller_test.go
  test/integration/elasticquota_controller_test.go
Labels: kind/feature, ok-to-test, size/XL, cncf-cla: yes, approved, release-note, lgtm

#566 Delete redundance package k8s.io/apimachinery/pkg/api/errors
  test/integration/utils.go
Labels: ok-to-test, cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS, release-note-none
