Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2023-02, with the labels that each got.

#492 Clean up unused variables and functions
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/coscheduling/core/core.go
  pkg/coscheduling/coscheduling.go
  pkg/networkaware/networkoverhead/networkoverhead_test.go
  pkg/trimaran/loadvariationriskbalancing/analysis_test.go
  pkg/util/podgroup_test.go
Labels: cncf-cla: yes, approved, size/M, kind/cleanup, lgtm, release-note-none

#493 Clean up nil error returns for the functions
  pkg/networkaware/networkoverhead/networkoverhead.go
  pkg/noderesourcetopology/filter_test.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/S, release-note-none

#494 Clean up unnecessary convert
  apis/config/v1/defaults.go
  apis/config/v1beta2/defaults.go
  apis/config/v1beta3/defaults.go
  pkg/noderesources/allocatable.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/S, release-note-none

#491 Remove unnecessary functions and optimize judgments
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/controller/podgroup_test.go
  pkg/networkaware/networkoverhead/networkoverhead.go
  pkg/networkaware/networkoverhead/networkoverhead_test.go
  pkg/networkaware/util/util.go
  pkg/preemptiontoleration/preemption_toleration.go
Labels: cncf-cla: yes, approved, size/M, kind/cleanup, lgtm, release-note-none

#496 Clean up missed nil error return definitions and judgments
  pkg/networkaware/networkoverhead/networkoverhead.go
  pkg/networkaware/topologicalsort/topologicalsort.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/S, release-note-none

#481 update 'update-codegen.sh' to make it works outside GOPATH
  config/crd/bases/scheduling.sigs.k8s.io_elasticquotas.yaml
  config/crd/bases/scheduling.sigs.k8s.io_podgroups.yaml
  hack/update-codegen.sh
Labels: kind/bug, ok-to-test, cncf-cla: yes, approved, size/M, lgtm, release-note-none

#502 Add compatibility matrix for NRT plugin
  pkg/noderesourcetopology/README.md
Labels: ok-to-test, cncf-cla: yes, kind/documentation, approved, size/M, lgtm, release-note-none

#476 networkAware update configs
  README.md
  cmd/scheduler/main.go
  kep/260-network-aware-scheduling/README.md
  manifests/appgroup/appgroup-controller-deployment.yaml
  manifests/appgroup/cluster-role.yaml
  manifests/appgroup/deploy.yaml
  manifests/appgroup/scheduler-config.yaml
  manifests/appgroup/scheduler-configmap-v1beta3.yaml
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/networktopology/cluster-role.yaml
  manifests/networktopology/deploy.yaml
  manifests/networktopology/networktopology-controller-deployment.yaml
  manifests/networktopology/scheduler-config.yaml
  manifests/networktopology/scheduler-configmap-v1beta3.yaml
  pkg/networkaware/README.md
  pkg/networkaware/networkoverhead/networkoverhead.go
  pkg/networkaware/topologicalsort/topologicalsort.go
Labels: ok-to-test, size/XL, cncf-cla: yes, approved, lgtm, release-note-none

#495 fix: math rendering in dark mode
  kep/61-Trimaran-real-load-aware-scheduling/README.md
Labels: cncf-cla: yes, kind/documentation, approved, lgtm, size/S, release-note-none

#498 Optimized error formatting and usestdlibvars
  cmd/scheduler/main_test.go
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/coscheduling/core/core.go
  pkg/networkaware/networkoverhead/networkoverhead.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/S, release-note-none

#510 update outdated doc
  doc/develop.md
Labels: ok-to-test, cncf-cla: yes, kind/documentation, approved, lgtm, size/XS, release-note-none

#497 fix the post-scheduler-plugins-push-images job error
  build/controller/Dockerfile
  build/scheduler/Dockerfile
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/XS, release-note-none

#509 CapacityScheduling: fix usedOverMinWith/usedOverMaxWith/usedOverMin func and add unit test
  pkg/capacityscheduling/elasticquota.go
  pkg/capacityscheduling/elasticquota_test.go
Labels: kind/bug, ok-to-test, size/L, cncf-cla: yes, approved, lgtm, release-note-none

#514 build: add script to build images
  Makefile
  hack/build-images.sh
Labels: ok-to-test, cncf-cla: yes, approved, size/M, lgtm, release-note-none

#506 feat: migrate podGroup controller to ctrl runtime
  cmd/controller/app/options.go
  cmd/controller/app/server.go
  go.mod
  pkg/controller/podgroup.go
  pkg/controllers/coscheduling/podgroup_controller.go
  pkg/controllers/podgroup_controller.go
  pkg/controllers/podgroup_test.go
  vendor/k8s.io/klog/v2/klogr/README.md
  vendor/k8s.io/klog/v2/klogr/klogr.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Labels: kind/feature, ok-to-test, tide/merge-method-squash, cncf-cla: yes, approved, release-note, lgtm, size/XXL

#520 CapacityScheduling: Fix default values for Max/Min in ElasticQuota
  pkg/capacityscheduling/capacity_scheduling_test.go
  pkg/capacityscheduling/elasticquota.go
  pkg/capacityscheduling/elasticquota_test.go
  test/integration/elasticquota_controller_test.go
Labels: kind/bug, ok-to-test, size/XL, tide/merge-method-squash, cncf-cla: yes, approved, lgtm, release-note-none

#526 ⚠️ BREAKING CHANGE: switch API group to x-k8s.io
  PROJECT
  apis/scheduling/doc.go
  apis/scheduling/groupversion_info.go
  apis/scheduling/v1alpha1/doc.go
  apis/scheduling/v1alpha1/groupversion_info.go
  apis/scheduling/v1alpha1/types.go
  config/crd/bases/scheduling.x-k8s.io_elasticquotas.yaml
  config/crd/bases/scheduling.x-k8s.io_podgroups.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_elasticquota.yaml
  config/crd/patches/cainjection_in_podgroups.yaml
  config/crd/patches/webhook_in_podgroups.yaml
  config/rbac/role.yaml
  doc/install.md
  hack/update-codegen.sh
  kep/2-lightweight-coscheduling/README.md
  kep/205-preemption-toleration/README.md
  kep/9-capacity-scheduling/README.md
  manifests/capacityscheduling/crd.yaml
  manifests/capacityscheduling/elasticquota-example.yaml
  manifests/coscheduling/crd.yaml
  manifests/crds/scheduling.x-k8s.io_elasticquotas.yaml
  manifests/crds/scheduling.x-k8s.io_podgroups.yaml
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  pkg/capacityscheduling/README.md
  pkg/controllers/CapacityScheduling/elasticquota_controller.go
  pkg/controllers/podgroup_controller.go
  pkg/coscheduling/README.md
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/elasticquota.go
  pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_elasticquota.go
  pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_podgroup.go
  pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/scheduling_client.go
  pkg/generated/informers/externalversions/generic.go
  pkg/preemptiontoleration/README.md
  pkg/preemptiontoleration/preemption_toleration_policy.go
  test/integration/capacity_scheduling_test.go
  test/integration/utils.go
Labels: size/L, cncf-cla: yes, approved, lgtm, kind/api-change, release-note-action-required

#523 fix: add "imagePullPolicy: IfNotPresent" in helmchart's kube-scheduler image
  manifests/install/charts/as-a-second-scheduler/templates/deployment.yaml
Labels: kind/bug, ok-to-test, cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS, release-note-none
