Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2023-11, with the labels that each got.

#654 Add namespace indexer to podInformer
  pkg/coscheduling/coscheduling.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS, release-note-none

#665 migrate elasticquota/capacityscheduling to controller-runtime
  Makefile
  cmd/scheduler/main_test.go
  hack/unit-test.sh
  pkg/capacityscheduling/capacity_scheduling.go
  test/integration/capacity_scheduling_test.go
  test/integration/elasticquota_controller_test.go
Labels: kind/feature, size/L, cncf-cla: yes, approved, kind/cleanup, release-note, lgtm

#669 Documents update for release v0.27.8
  README.md
  doc/install.md
  manifests/appgroup/deploy-sig-scheduling-controller-and-scheduler.yaml
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
  manifests/networktopology/deploy-sig-scheduling-controller-and-scheduler.yaml
  site/content/en/_index.md
  site/content/en/docs/user-guide/installation.md
  site/content/en/docs/user-guide/installing-the-chart.md
Labels: cncf-cla: yes, kind/documentation, approved, size/M, lgtm, release-note-none

#672 Coscheduling: Remove the postBind filter in the KubeSchedulerConfiguration
  manifests/coscheduling/scheduler-config.yaml
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS, release-note-none

#675 [release-1.27] update typed client and informer
  go.mod
  pkg/generated/applyconfiguration/internal/internal.go
  pkg/generated/applyconfiguration/scheduling/v1alpha1/elasticquota.go
  pkg/generated/applyconfiguration/scheduling/v1alpha1/elasticquotaspec.go
  pkg/generated/applyconfiguration/scheduling/v1alpha1/elasticquotastatus.go
  pkg/generated/applyconfiguration/scheduling/v1alpha1/podgroup.go
  pkg/generated/applyconfiguration/scheduling/v1alpha1/podgroupspec.go
  pkg/generated/applyconfiguration/scheduling/v1alpha1/podgroupstatus.go
  pkg/generated/applyconfiguration/utils.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/elasticquota.go
  pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_elasticquota.go
  pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_podgroup.go
  pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/podgroup.go
  pkg/generated/informers/externalversions/factory.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XXL, release-note-none

#674 Automated cherry pick of #669: doc update for v0.27
  README.md
  doc/install.md
  manifests/appgroup/deploy-sig-scheduling-controller-and-scheduler.yaml
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
  manifests/networktopology/deploy-sig-scheduling-controller-and-scheduler.yaml
  site/content/en/_index.md
  site/content/en/docs/user-guide/installation.md
  site/content/en/docs/user-guide/installing-the-chart.md
Labels: cncf-cla: yes, approved, size/M, lgtm, release-note-none

#677 Automated cherry pick of #672: Coscheduling: Remove the postBind filter in the
  manifests/coscheduling/scheduler-config.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS, release-note-none

#678 Automated cherry pick of #672: Coscheduling: Remove the postBind filter in the
  manifests/coscheduling/scheduler-config.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS, release-note-none
