Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2024-07, with the labels that each got.

#746 Add support for ppc64le and s390x architectures and distroless builds
  Makefile
  build/controller/Dockerfile
  build/scheduler/Dockerfile
  hack/build-images.sh
Labels: kind/feature, ok-to-test, size/L, cncf-cla: yes, approved, release-note, lgtm

#766 Enable buildx in cloudbuild
  cloudbuild.yaml
Labels: kind/bug, cncf-cla: yes, approved, size/XS, release-note-none, kind/regression

#767 fix buildx command in cloudbuild
  hack/build-images.sh
Labels: kind/bug, cncf-cla: yes, approved, size/M, lgtm, release-note-none

#768 increase the timeout of cloudbuild
  cloudbuild.yaml
Labels: cncf-cla: yes, approved, kind/cleanup, size/XS, release-note-none

#769 use high memory machine to speedup cloudbuild
  cloudbuild.yaml
Labels: kind/feature, cncf-cla: yes, approved, size/XS, release-note-none

#770 revert building platforms for linux/s390x and linux/ppc64le
  Makefile
Labels: cncf-cla: yes, approved, kind/cleanup, size/XS, release-note-none

#764 chore: fix EventsToRegister method comment
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/coscheduling/coscheduling.go
  pkg/noderesourcetopology/plugin.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS, release-note-none

#771 revamp Makefile and build scripts to adapt to 'docker buildx' in local and cloudbuild
  Makefile
  build/controller/Dockerfile
  build/scheduler/Dockerfile
  cloudbuild.yaml
  hack/build-images.sh
Labels: kind/feature, cncf-cla: yes, approved, size/M, release-note

#772 extend build platforms to include linux/s390x,linux/ppc64le
  Makefile
Labels: kind/feature, cncf-cla: yes, approved, size/XS, release-note-none

#773 speed up build time using platform specific image/arguments
  Makefile
  build/controller/Dockerfile
  build/scheduler/Dockerfile
  hack/build-images.sh
Labels: kind/feature, cncf-cla: yes, approved, size/M, release-note-none

#774 bump k8s deps to v1.29.7
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/interface.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/preemption/preemption.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/types.go
  vendor/k8s.io/kubernetes/pkg/scheduler/internal/queue/scheduling_queue.go
  vendor/k8s.io/kubernetes/pkg/scheduler/schedule_one.go
  vendor/k8s.io/kubernetes/pkg/scheduler/scheduler.go
  vendor/k8s.io/kubernetes/pkg/scheduler/testing/wrappers.go
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/defaultfs.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_unix.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_windows.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-attacher/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-health-monitor/external-health-monitor-controller/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-provisioner/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-resizer/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-snapshotter/csi-snapshotter/rbac-csi-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/README.md
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-driverinfo.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-testing.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/update-hostpath.sh
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: size/XL, cncf-cla: yes, approved, kind/cleanup, release-note-none

#775 doc update for v0.29.7
  README.md
  doc/install.md
  manifests/appgroup/deploy-sig-scheduling-controller-and-scheduler.yaml
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
  manifests/networktopology/deploy-sig-scheduling-controller-and-scheduler.yaml
  site/content/en/_index.md
  site/content/en/docs/user-guide/installation.md
  site/content/en/docs/user-guide/installing-the-chart.md
Labels: size/L, cncf-cla: yes, kind/documentation, approved, release-note-none

#777 Fix an issue that build params are not propagated
  Makefile
  build/controller/Dockerfile
  build/scheduler/Dockerfile
Labels: kind/bug, cncf-cla: yes, approved, size/S, release-note-none

#780 update Helm's deployment spec
  doc/develop.md
  manifests/appgroup/deploy-sig-scheduling-controller-and-scheduler.yaml
  manifests/install/charts/as-a-second-scheduler/templates/deployment.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
  manifests/networktopology/deploy-sig-scheduling-controller-and-scheduler.yaml
  manifests/noderesourcetopology/deploy.yaml
  site/content/en/docs/user-guide/develop.md
Labels: cncf-cla: yes, approved, kind/cleanup, size/S, release-note-none

#782 Update helm chart's version to 0.29.7
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
Labels: cncf-cla: yes, kind/documentation, approved, size/XS, release-note-none

#784 fix image URLs in Helm chart
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: cncf-cla: yes, approved, kind/cleanup, size/XS, release-note-none

#786 update helm chart index to include version 0.29.7
  manifests/install/charts/as-a-second-scheduler/README.md
  site/content/en/docs/user-guide/installing-the-chart.md
  site/static/index.yaml
Labels: cncf-cla: yes, kind/documentation, approved, release-note, size/S

#787 add back previous Helm release entry
  site/static/index.yaml
Labels: cncf-cla: yes, approved, kind/cleanup, size/S, release-note-none
