Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2024-04, with the labels that each got.

#697 Add scheduling op to helm chart
  hack/install-envtest.sh
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/deployment.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: kind/feature, cncf-cla: yes, approved, size/M, release-note, lgtm

#716 Documents update for release v0.28.8
  README.md
  doc/install.md
  manifests/appgroup/deploy-sig-scheduling-controller-and-scheduler.yaml
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
  manifests/networktopology/deploy-sig-scheduling-controller-and-scheduler.yaml
  site/content/en/_index.md
  site/content/en/docs/user-guide/installation.md
  site/content/en/docs/user-guide/installing-the-chart.md
Labels: cncf-cla: yes, kind/documentation, approved, size/M, lgtm, release-note-none

#700 Avoid unnecessary requeue operations in coscheduling
  pkg/coscheduling/core/core.go
  pkg/coscheduling/core/core_test.go
  pkg/coscheduling/coscheduling.go
Labels: kind/bug, cncf-cla: yes, approved, size/M, release-note, lgtm

#719 Documents update for release v0.28.9
  README.md
  doc/install.md
  manifests/appgroup/deploy-sig-scheduling-controller-and-scheduler.yaml
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
  manifests/networktopology/deploy-sig-scheduling-controller-and-scheduler.yaml
  site/content/en/_index.md
  site/content/en/docs/user-guide/installation.md
  site/content/en/docs/user-guide/installing-the-chart.md
Labels: cncf-cla: yes, kind/documentation, approved, size/M, lgtm, release-note-none

#710 [noderesourcetopology] move logging to the logr interface
  go.mod
  go.sum
  pkg/noderesourcetopology/cache/discardreserved.go
  pkg/noderesourcetopology/cache/discardreserved_test.go
  pkg/noderesourcetopology/cache/foreign_pods.go
  pkg/noderesourcetopology/cache/foreign_pods_test.go
  pkg/noderesourcetopology/cache/overreserve.go
  pkg/noderesourcetopology/cache/overreserve_test.go
  pkg/noderesourcetopology/cache/passthrough.go
  pkg/noderesourcetopology/cache/passthrough_test.go
  pkg/noderesourcetopology/cache/store.go
  pkg/noderesourcetopology/cache/store_test.go
  pkg/noderesourcetopology/config.go
  pkg/noderesourcetopology/config_test.go
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/filter_test.go
  pkg/noderesourcetopology/least_numa.go
  pkg/noderesourcetopology/least_numa_test.go
  pkg/noderesourcetopology/logging.go
  pkg/noderesourcetopology/logging/logging.go
  pkg/noderesourcetopology/plugin.go
  pkg/noderesourcetopology/pluginhelpers.go
  pkg/noderesourcetopology/pluginhelpers_test.go
  pkg/noderesourcetopology/podprovider/podprovider.go
  pkg/noderesourcetopology/postbind.go
  pkg/noderesourcetopology/reserve.go
  pkg/noderesourcetopology/score.go
  pkg/noderesourcetopology/score_test.go
  pkg/noderesourcetopology/stringify/stringify.go
  pkg/noderesourcetopology/stringify/stringify_test.go
  vendor/github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha2/helper/numanode/numanode.go
  vendor/modules.txt
Labels: kind/feature, size/XL, cncf-cla: yes, approved, lgtm, release-note-none
