Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2024-08, with the labels that each got.

#790 add subtitle for trimaran in plugin list
  README.md
Labels: ok-to-test, cncf-cla: yes, kind/documentation, approved, lgtm, size/XS, release-note-none

#794 use `/bin/kube-scheduler` and `/bin/controller` as the entrypoints of Dockerfiles
  build/controller/Dockerfile
  build/scheduler/Dockerfile
  manifests/appgroup/deploy-appgroup-controller.yaml
  manifests/networktopology/deploy-networktopology-controller.yaml
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/S, release-note-none

#796 [release-1.29] bump k8s deps to v1.29.8
  go.mod
  go.sum
  vendor/k8s.io/api/admissionregistration/v1alpha1/types.go
  vendor/k8s.io/api/admissionregistration/v1beta1/types.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/code-generator/generate-internal-groups.sh
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/scheduling/nvidia-driver-installer.yaml
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/modules.txt
Labels: size/L, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none

#755 solve struct literal uses unkeyed fields
  pkg/networkaware/networkoverhead/networkoverhead_test.go
  pkg/networkaware/topologicalsort/topologicalsort_test.go
  test/integration/networkoverhead_test.go
  test/integration/topologicalsort_test.go
Labels: ok-to-test, cncf-cla: yes, approved, size/M, kind/cleanup, lgtm, release-note-none, lifecycle/stale
