Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2024-11, with the labels that each got.

#802 allow resources to be configured in Helm chart
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/deployment.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: kind/feature, ok-to-test, cncf-cla: yes, approved, lgtm, size/S, release-note-none

#805 fix: fix wrong PreemptionToleration policy example
  pkg/preemptiontoleration/README.md
Labels: ok-to-test, cncf-cla: yes, kind/documentation, approved, lgtm, size/XS, release-note-none

#817 bump k8s deps to v1.30.6
  go.mod
  go.sum
  vendor/go.opentelemetry.io/otel/metric/noop/noop.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/apiserver/pkg/server/options/tracing.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/code-generator/tools.go
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/args/args.go
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go
  vendor/k8s.io/kube-openapi/pkg/generators/README.md
  vendor/k8s.io/kube-openapi/pkg/generators/api_linter.go
  vendor/k8s.io/kube-openapi/pkg/generators/config.go
  vendor/k8s.io/kube-openapi/pkg/generators/enum.go
  vendor/k8s.io/kube-openapi/pkg/generators/extension.go
  vendor/k8s.io/kube-openapi/pkg/generators/markers.go
  vendor/k8s.io/kube-openapi/pkg/generators/openapi.go
  vendor/k8s.io/kube-openapi/pkg/generators/rules/OWNERS
  vendor/k8s.io/kube-openapi/pkg/generators/rules/doc.go
  vendor/k8s.io/kube-openapi/pkg/generators/rules/idl_tag.go
  vendor/k8s.io/kube-openapi/pkg/generators/rules/names_match.go
  vendor/k8s.io/kube-openapi/pkg/generators/rules/omitempty_match_case.go
  vendor/k8s.io/kube-openapi/pkg/generators/union.go
  vendor/k8s.io/kube-openapi/pkg/util/sets/empty.go
  vendor/k8s.io/kube-openapi/pkg/util/sets/string.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/preemption/preemption.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XXL, release-note-none

#813 feature: use contextal logging
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/capacityscheduling/capacity_scheduling_test.go
  pkg/coscheduling/core/core.go
  pkg/coscheduling/coscheduling.go
  pkg/networkaware/networkoverhead/networkoverhead.go
  pkg/networkaware/topologicalsort/topologicalsort.go
  pkg/noderesources/allocatable.go
  pkg/noderesources/resource_allocation.go
  pkg/preemptiontoleration/preemption_toleration.go
  pkg/sysched/sysched.go
  pkg/sysched/sysched_test.go
  pkg/trimaran/collector.go
  pkg/trimaran/collector_test.go
  pkg/trimaran/handler.go
  pkg/trimaran/loadvariationriskbalancing/analysis.go
  pkg/trimaran/loadvariationriskbalancing/analysis_test.go
  pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing.go
  pkg/trimaran/lowriskovercommitment/lowriskovercommitment.go
  pkg/trimaran/lowriskovercommitment/lowriskovercommitment_test.go
  pkg/trimaran/resourcestats.go
  pkg/trimaran/resourcestats_test.go
  pkg/trimaran/targetloadpacking/targetloadpacking.go
Labels: kind/feature, size/XL, cncf-cla: yes, approved, lgtm, release-note-none

#822 update helm chart index to include version 0.30.6
  site/static/index.yaml
Labels: cncf-cla: yes, kind/documentation, approved, lgtm, size/S, release-note-none

#818 Dynamically add required RBAC in Helm chart
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
Labels: kind/bug, ok-to-test, cncf-cla: yes, approved, size/M, release-note, lgtm

#824 allow priorityClassName to be configured in Helm chart
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/templates/deployment.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
  site/content/en/docs/user-guide/installing-the-chart.md
Labels: kind/feature, ok-to-test, cncf-cla: yes, approved, size/M, release-note, lgtm

#823 feature: use contextal logging for integration
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/networkaware/networkoverhead/networkoverhead.go
  pkg/noderesources/allocatable.go
  pkg/noderesourcetopology/cache/attr_watch.go
  pkg/trimaran/resourcestats.go
  test/integration/allocatable_test.go
  test/integration/capacity_scheduling_test.go
  test/integration/coscheduling_test.go
  test/integration/elasticquota_controller_test.go
  test/integration/loadVariationRiskBalancing_test.go
  test/integration/lowriskovercommitment_test.go
  test/integration/networkoverhead_test.go
  test/integration/noderesourcetopology_cache_test.go
  test/integration/noderesourcetopology_test.go
  test/integration/nrtutils.go
  test/integration/pod_state_test.go
  test/integration/podgroup_controller_test.go
  test/integration/preemption_toleration_test.go
  test/integration/sysched_test.go
  test/integration/targetloadpacking_test.go
  test/integration/utils.go
Labels: size/L, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none

#825 migrate misplaced RBAC in Helm chart
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
Labels: kind/bug, ok-to-test, cncf-cla: yes, approved, lgtm, size/S, release-note-none

#831 chore: renew verify conextual structured script
  hack/verify-structured-logging.sh
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/S, release-note-none

#827 Allow leader election for scheduler-plugins-controller in Helm chart
  manifests/install/charts/as-a-second-scheduler/templates/deployment.yaml
  manifests/install/charts/as-a-second-scheduler/templates/rbac.yaml
  manifests/install/charts/as-a-second-scheduler/values.yaml
Labels: kind/feature, ok-to-test, cncf-cla: yes, approved, lgtm, size/XS, release-note-none
