Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2024-05, with the labels that each got.

#728 pass existing context without using TODO()
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/noderesourcetopology/cache/overreserve.go
  pkg/noderesourcetopology/cache/overreserve_test.go
  pkg/noderesourcetopology/plugin.go
  pkg/noderesourcetopology/pluginhelpers.go
  pkg/sysched/sysched.go
Labels: cncf-cla: yes, approved, size/M, kind/cleanup, lgtm, release-note-none

#725 [noderesourcetopology] complete the contextual logging integration
  pkg/noderesourcetopology/cache/discardreserved.go
  pkg/noderesourcetopology/cache/foreign_pods.go
  pkg/noderesourcetopology/cache/overreserve.go
  pkg/noderesourcetopology/cache/store.go
  pkg/noderesourcetopology/cache/store_test.go
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/logging/logging.go
  pkg/noderesourcetopology/plugin.go
  pkg/noderesourcetopology/pluginhelpers.go
  pkg/noderesourcetopology/podprovider/podprovider.go
  pkg/noderesourcetopology/postbind.go
  pkg/noderesourcetopology/reserve.go
  pkg/noderesourcetopology/score.go
Labels: size/L, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none

#726 fix log print and some nit issue
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/noderesourcetopology/cache/cache.go
  pkg/podstate/pod_state.go
  pkg/sysched/sysched_test.go
  pkg/trimaran/README.md
  pkg/trimaran/targetloadpacking/targetloadpacking.go
Labels: ok-to-test, cncf-cla: yes, approved, kind/cleanup, lgtm, size/S, release-note-none

#735 [noderesourcetopology] improve classification of resources
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/numaresources.go
  pkg/noderesourcetopology/numaresources_test.go
Labels: size/L, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none

#737 site: add chart index to site
  site/static/index.yaml
Labels: cncf-cla: yes, kind/documentation, approved, release-note, lgtm, size/S, area/helm

#738 Add ARG for base image customization
  Makefile
  build/controller/Dockerfile
  build/scheduler/Dockerfile
  hack/build-images.sh
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/S, release-note-none

#731 add crd(podgroup, elasticquotas) field
  apis/scheduling/v1alpha1/types.go
  config/crd/bases/scheduling.x-k8s.io_elasticquotas.yaml
  config/crd/bases/scheduling.x-k8s.io_podgroups.yaml
  manifests/capacityscheduling/crd.yaml
  manifests/coscheduling/crd.yaml
Labels: kind/feature, tide/merge-method-squash, cncf-cla: yes, approved, size/M, lgtm, release-note-none

#747 Revert "generate-internal-groups.sh -> kube_codegen.sh"
  go.mod
  hack/update-codegen.sh
  pkg/generated/applyconfiguration/internal/internal.go
  pkg/generated/applyconfiguration/scheduling/v1alpha1/elasticquota.go
  pkg/generated/applyconfiguration/scheduling/v1alpha1/elasticquotaspec.go
  pkg/generated/applyconfiguration/scheduling/v1alpha1/elasticquotastatus.go
  pkg/generated/applyconfiguration/scheduling/v1alpha1/podgroup.go
  pkg/generated/applyconfiguration/scheduling/v1alpha1/podgroupspec.go
  pkg/generated/applyconfiguration/scheduling/v1alpha1/podgroupstatus.go
  pkg/generated/applyconfiguration/utils.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/doc.go
  pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/elasticquota.go
  pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_elasticquota.go
  pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_podgroup.go
  pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/podgroup.go
  pkg/generated/informers/externalversions/factory.go
  vendor/k8s.io/code-generator/generate-internal-groups.sh
Labels: kind/bug, cncf-cla: yes, approved, size/XXL, release-note-none, kind/regression

#736 docs: anyone should be any
  apis/scheduling/v1alpha1/types.go
  config/crd/bases/scheduling.x-k8s.io_podgroups.yaml
  kep/42-podgroup-coscheduling/README.md
  manifests/coscheduling/crd.yaml
  site/content/en/docs/kep/42-podgroup-coscheduling/README.md
Labels: ok-to-test, cncf-cla: yes, kind/documentation, approved, lgtm, size/S, release-note-none

#739 replace deprecated method
  pkg/controllers/elasticquota_controller_test.go
  pkg/networkaware/networkoverhead/networkoverhead_test.go
  test/integration/allocatable_test.go
  test/integration/capacity_scheduling_test.go
  test/integration/coscheduling_test.go
  test/integration/elasticquota_controller_test.go
  test/integration/loadVariationRiskBalancing_test.go
  test/integration/lowriskovercommitment_test.go
  test/integration/networkoverhead_test.go
  test/integration/noderesourcetopology_cache_test.go
  test/integration/noderesourcetopology_test.go
  test/integration/nrtutils.go
  test/integration/pod_state_test.go
  test/integration/podgroup_controller_test.go
  test/integration/preemption_toleration_test.go
  test/integration/qos_test.go
  test/integration/sysched_test.go
  test/integration/targetloadpacking_test.go
  test/integration/topologicalsort_test.go
  test/integration/utils.go
Labels: size/L, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none

#750 Fix typo: gochache => gocache
  pkg/coscheduling/core/core.go
  pkg/coscheduling/core/core_test.go
Labels: ok-to-test, cncf-cla: yes, approved, kind/cleanup, lgtm, size/S, release-note-none

#749 bump codegen to 0.14.0
  apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/scheduling.x-k8s.io_elasticquotas.yaml
  config/crd/bases/scheduling.x-k8s.io_podgroups.yaml
  hack/update-codegen.sh
  hack/verify-crdgen.sh
  manifests/appgroup/crd.yaml
  manifests/capacityscheduling/crd.yaml
  manifests/coscheduling/crd.yaml
  manifests/crds/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
  manifests/networktopology/crd.yaml
  manifests/noderesourcetopology/crd.yaml
Labels: size/L, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none

#752 [noderesourcetopology] rewrite accounting of numa-affine resources with scope=container
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/logging/logging.go
  pkg/noderesourcetopology/numaresources.go
  pkg/noderesourcetopology/numaresources_test.go
  pkg/noderesourcetopology/plugin.go
  pkg/noderesourcetopology/plugin_test.go
  pkg/noderesourcetopology/stringify/stringify.go
  pkg/noderesourcetopology/stringify/stringify_test.go
  test/integration/noderesourcetopology_test.go
  test/integration/nrtutils.go
Labels: kind/bug, size/XL, cncf-cla: yes, approved, release-note, lgtm
