Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2024-01, with the labels that each got.

#692 CI: add releasing helm chart
  .github/workflows/helm.yaml
Labels: kind/feature, cncf-cla: yes, approved, release-note, lgtm, size/S

#680 docs: update the version of scheduler config and use MultiPoint to simplify them
  manifests/appgroup/scheduler-config.yaml
  manifests/capacityscheduling/scheduler-config.yaml
  manifests/coscheduling/scheduler-config.yaml
  manifests/networktopology/scheduler-config.yaml
  manifests/noderesources/scheduler-config.yaml
  manifests/noderesourcetopology/scheduler-configmap.yaml
  manifests/podstate/scheduler-config.yaml
  pkg/capacityscheduling/README.md
  pkg/coscheduling/README.md
  pkg/crossnodepreemption/README.md
  pkg/networkaware/README.md
  pkg/networkaware/networkoverhead/README.md
  pkg/networkaware/topologicalsort/README.md
  pkg/noderesources/README.md
  pkg/noderesourcetopology/README.md
  pkg/podstate/README.md
  pkg/preemptiontoleration/README.md
  site/content/en/docs/plugins/capacity-scheduling.md
  site/content/en/docs/plugins/coscheduling.md
  site/content/en/docs/plugins/crossnodepreemption.md
  site/content/en/docs/plugins/networkaware.md
  site/content/en/docs/plugins/networkoverhead.md
  site/content/en/docs/plugins/noderesources.md
  site/content/en/docs/plugins/noderesourcetopology.md
  site/content/en/docs/plugins/podstate.md
  site/content/en/docs/plugins/preemptiontoleration.md
  site/content/en/docs/plugins/topologicalsort.md
Labels: size/L, cncf-cla: yes, kind/documentation, approved, kind/cleanup, lgtm, release-note-none

#693 [release-1.27] bump k8s deps to v1.27.9
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/endpoints/discovery/aggregated/handler.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/runtime/framework.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/types.go
  vendor/k8s.io/kubernetes/pkg/scheduler/schedule_one.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: size/L, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none

#687 Update api version and field for noderesourcetopology
  manifests/noderesourcetopology/worker-node-A.yaml
  manifests/noderesourcetopology/worker-node-B.yaml
  pkg/noderesourcetopology/README.md
  site/content/en/docs/plugins/noderesourcetopology.md
Labels: cncf-cla: yes, kind/documentation, approved, size/M, lgtm, release-note-none

#599 nrt: cache: add support for dedicated informer
  apis/config/types.go
  apis/config/v1/defaults.go
  apis/config/v1/defaults_test.go
  apis/config/v1/types.go
  apis/config/v1/zz_generated.conversion.go
  apis/config/v1/zz_generated.deepcopy.go
  apis/config/v1beta3/defaults.go
  apis/config/v1beta3/defaults_test.go
  apis/config/v1beta3/types.go
  apis/config/v1beta3/zz_generated.conversion.go
  apis/config/v1beta3/zz_generated.deepcopy.go
  apis/config/zz_generated.deepcopy.go
  pkg/noderesourcetopology/cache/overreserve.go
  pkg/noderesourcetopology/cache/overreserve_test.go
  pkg/noderesourcetopology/cache/store.go
  pkg/noderesourcetopology/cache/store_test.go
  pkg/noderesourcetopology/pluginhelpers.go
  pkg/noderesourcetopology/podprovider/podprovider.go
Labels: kind/bug, do-not-merge/hold, size/XL, cncf-cla: yes, approved, lgtm, kind/api-change, release-note-none

#698 Remove incorrect Pod name from installation doc
  doc/install.md
Labels: cncf-cla: yes, kind/documentation, approved, kind/cleanup, lgtm, size/XS, release-note-none

#699 remove manual edit strings from crd manifests
  hack/verify-crdgen.sh
  manifests/appgroup/crd.yaml
  manifests/networktopology/crd.yaml
Labels: cncf-cla: yes, approved, kind/cleanup, release-note, lgtm, size/XS
