Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2024-06, with the labels that each got.

#753 add unit-test.sh args customizable
  Makefile
  hack/unit-test.sh
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS, release-note-none

#754 Convert update-codegen.sh to new codegen
  hack/update-codegen.sh
Labels: kind/feature, ok-to-test, cncf-cla: yes, approved, size/M, lgtm, release-note-none

#631 [noderesourcetopology] update NRT when attributes change
  apis/config/types.go
  apis/config/v1/types.go
  pkg/noderesourcetopology/cache/attr_watch.go
  pkg/noderesourcetopology/cache/attr_watch_test.go
  pkg/noderesourcetopology/cache/cache_test.go
  pkg/noderesourcetopology/cache/discardreserved_test.go
  pkg/noderesourcetopology/cache/overreserve.go
  pkg/noderesourcetopology/cache/overreserve_test.go
  pkg/noderesourcetopology/cache/passthrough_test.go
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/nodeconfig/topologymanager.go
  pkg/noderesourcetopology/nodeconfig/topologymanager_test.go
  pkg/noderesourcetopology/pluginhelpers.go
  pkg/noderesourcetopology/score.go
  test/integration/noderesourcetopology_cache_test.go
  test/integration/noderesourcetopology_test.go
  test/util/fake.go
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/XXL, release-note-none

#758 fix: add validation for pggroup
  apis/scheduling/v1alpha1/types.go
  config/crd/bases/scheduling.x-k8s.io_podgroups.yaml
  manifests/coscheduling/crd.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/XS, release-note-none
