Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2025-04, with the labels that each got.

#883 chore: add more contextual logging info for plugins
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/coscheduling/coscheduling.go
  pkg/networkaware/networkoverhead/networkoverhead.go
  pkg/networkaware/topologicalsort/topologicalsort.go
  pkg/noderesources/allocatable.go
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/plugin.go
  pkg/noderesourcetopology/postbind.go
  pkg/noderesourcetopology/reserve.go
  pkg/noderesourcetopology/score.go
  pkg/preemptiontoleration/preemption_toleration.go
  pkg/preemptiontoleration/preemption_toleration_test.go
  pkg/sysched/sysched.go
  pkg/sysched/sysched_test.go
  pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing.go
  pkg/trimaran/lowriskovercommitment/lowriskovercommitment.go
  pkg/trimaran/peaks/peaks.go
  pkg/trimaran/targetloadpacking/targetloadpacking.go
Labels: size/L, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none

#889 nominate googs1025 for scheduler-plugins reviewers
  OWNERS
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS, release-note-none

#893 [release-1.30] bump k8s deps to v1.30.12
  README.md
  doc/install.md
  go.mod
  go.sum
  manifests/appgroup/deploy-sig-scheduling-controller-and-scheduler.yaml
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/values.yaml
  manifests/networktopology/deploy-sig-scheduling-controller-and-scheduler.yaml
  site/content/en/_index.md
  site/content/en/docs/user-guide/installation.md
  site/content/en/docs/user-guide/installing-the-chart.md
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go
  vendor/k8s.io/apiserver/pkg/server/options/etcd.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  vendor/k8s.io/component-base/metrics/prometheus/slis/routes.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/types.go
  vendor/k8s.io/kubernetes/pkg/scheduler/extender.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/binder.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/fake_binder.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go
  vendor/k8s.io/kubernetes/pkg/scheduler/internal/cache/cache.go
  vendor/k8s.io/kubernetes/pkg/scheduler/testing/wrappers.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer_unsupported.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/recyclerclient/recycler_client.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/modules.txt
Labels: kind/bug, size/XL, cncf-cla: yes, approved, kind/cleanup, release-note, lgtm

#894 bump k8s deps to v1.31.8
  go.mod
  go.sum
Labels: size/L, cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none

#895 Compose a cached reader as a cacheOption when initializing a controller-runtime client
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/coscheduling/coscheduling.go
  pkg/networkaware/networkoverhead/networkoverhead.go
  pkg/networkaware/topologicalsort/topologicalsort.go
  pkg/sysched/sysched.go
  pkg/util/client_util.go
  test/integration/capacity_scheduling_test.go
  test/integration/coscheduling_test.go
  test/integration/elasticquota_controller_test.go
  test/integration/networkoverhead_test.go
  test/integration/podgroup_controller_test.go
  test/integration/sysched_test.go
  test/integration/topologicalsort_test.go
  test/util/fake.go
Labels: kind/bug, cncf-cla: yes, approved, size/M, release-note, lgtm

#896 Automated cherry pick of #895: Compose a cached reader as a cacheOption when initializing a
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/coscheduling/coscheduling.go
  pkg/networkaware/networkoverhead/networkoverhead.go
  pkg/networkaware/topologicalsort/topologicalsort.go
  pkg/sysched/sysched.go
  pkg/util/client_util.go
  test/integration/capacity_scheduling_test.go
  test/integration/coscheduling_test.go
  test/integration/elasticquota_controller_test.go
  test/integration/networkoverhead_test.go
  test/integration/podgroup_controller_test.go
  test/integration/sysched_test.go
  test/integration/topologicalsort_test.go
  test/util/fake.go
Labels: size/L, cncf-cla: yes, approved, release-note, lgtm

#897 clientutil: verify if cache is synced
  pkg/util/client_util.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS, release-note-none

#899 clientutil: fix a typo
  pkg/util/client_util.go
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS, release-note-none

#900 helm: update the helm chart's index to include 0.30.12
  site/static/index.yaml
Labels: cncf-cla: yes, kind/documentation, approved, release-note, lgtm, size/S, area/helm

#898 doc update for v0.31.8
  README.md
  doc/install.md
  manifests/appgroup/deploy-sig-scheduling-controller-and-scheduler.yaml
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/values.yaml
  manifests/networktopology/deploy-sig-scheduling-controller-and-scheduler.yaml
  site/content/en/_index.md
  site/content/en/docs/user-guide/installation.md
  site/content/en/docs/user-guide/installing-the-chart.md
Labels: size/L, cncf-cla: yes, kind/documentation, approved, lgtm, release-note-none

#903 re-update helm chart index to include version 0.31.8
  site/static/index.yaml
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS, release-note-none, area/helm

#904 fix: update the mailing list address
  RELEASE.md
Labels: cncf-cla: yes, kind/documentation, approved, lgtm, size/XS, release-note-none
