Repository kubernetes-sigs/scheduler-plugins, pull requests merged in 2025-01, with the labels that each got.

#708 cache assigned pod count
  pkg/coscheduling/core/core.go
  pkg/coscheduling/core/core_test.go
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
  test/integration/coscheduling_test.go
Labels: kind/feature, ok-to-test, size/L, tide/merge-method-squash, cncf-cla: yes, approved, release-note, lgtm

#855 fix(QOSSort): refine queue sorting logic by adding inqueue timestamp
  pkg/qos/queue_sort.go
  pkg/qos/queue_sort_test.go
  test/integration/qos_test.go
Labels: kind/bug, size/L, cncf-cla: yes, approved, lgtm, release-note-none

#861 flake: fix qos sort plugin flaky integration test
  test/integration/qos_test.go
Labels: cncf-cla: yes, approved, lgtm, kind/flake, size/XS, release-note-none

#857 CVE-2024-45338: uplift golang.org/x/net version to 0.33.0
  go.mod
  go.sum
Labels: kind/bug, ok-to-test, tide/merge-method-squash, cncf-cla: yes, approved, size/M, release-note, lgtm

#866 feature: add more integation test case for qos sort plugin
  test/integration/qos_test.go
Labels: kind/feature, size/L, cncf-cla: yes, approved, lgtm, release-note-none
